import { browserIconSvg } from "./browser-icons";

// Page strings only ever reach textContent, value, or the BB composer through postMessage.
export const viewerAnnotationCss = String.raw`
#annotation-layer{position:absolute;inset:0;z-index:5;display:none;cursor:crosshair;touch-action:none}
#viewport[data-annotating="true"] #annotation-layer{display:block}
#viewport[data-annotating="true"] #control-overlay{display:none}
#annotation-hover{position:absolute;display:none;border:1.5px solid var(--annotation,#3b82f6);border-radius:2px;background:color-mix(in srgb,var(--annotation,#3b82f6) 10%,transparent);pointer-events:none}
#annotation-hover[data-active="true"]{display:block}
#annotation-hover[data-selected="true"]{border-width:2px;background:color-mix(in srgb,var(--annotation,#3b82f6) 16%,transparent)}
.annotation-marker{position:absolute;width:22px;height:22px;margin:-11px 0 0 -11px;display:grid;place-items:center;border:2px solid #fff;border-radius:50% 50% 50% 4px;background:var(--annotation,#3b82f6);color:#fff;font:600 11px/1 system-ui,sans-serif;box-shadow:0 1px 4px #0006;cursor:pointer;padding:0}
.annotation-marker[hidden]{display:none}
.annotation-marker:hover,.annotation-marker[data-editing="true"]{transform:scale(1.12)}
#annotation-bubble{position:fixed;z-index:20;display:flex;align-items:center;gap:4px;width:min(380px,calc(100vw - 16px));height:48px;margin:0;padding:0 8px 0 14px;border:1px solid var(--border,#ffffff18);border-radius:calc(var(--radius,.5rem) + 4px);background:var(--background,#0b0b0d);color:var(--foreground,#fafafa);box-shadow:var(--shadow-lift,0 -4px 12px -4px #00000042),0 8px 24px -8px #0006}
#annotation-bubble[hidden]{display:none}
#annotation-comment{flex:1;min-width:0;height:100%;margin:0;padding:0;border:0;border-radius:0;outline:0;background:transparent;color:inherit;font:inherit;font-size:14px;box-shadow:none}
#annotation-comment:hover,#annotation-comment:focus{background:transparent}
#annotation-comment::placeholder{color:var(--muted-foreground,#a1a1aa)}
#annotation-action{flex:none;width:32px;height:32px;padding:0;border-radius:calc(var(--radius,.5rem) - 2px);display:inline-flex;align-items:center;justify-content:center;background:var(--foreground,#fafafa);color:var(--background,#0b0b0d)}
#annotation-action:hover{background:color-mix(in srgb,var(--foreground,#fafafa) 90%,transparent);color:var(--background,#0b0b0d)}
#annotation-action:disabled{opacity:.5;pointer-events:none}
#annotation-action:focus-visible{outline:1px solid var(--ring,#71717a);outline-offset:1px}
#annotation-action[data-mode="recording"]{background:var(--secondary,#27272a);color:var(--secondary-foreground,#fafafa)}
#annotation-action[data-mode="recording"]:hover{background:color-mix(in srgb,var(--secondary,#27272a) 80%,transparent)}
#annotation-action[data-mode="recording"] svg{width:14px;height:14px;fill:currentColor}
#annotation-action[data-mode="recording"] svg *{stroke-width:0}
#annotation-action[data-mode="busy"] svg{animation:spin 1s linear infinite}
#annotation-action svg{width:16px;height:16px}
`;

export const viewerAnnotationToolbarButton = `<button id="annotate-toggle" title="Annotate" aria-label="Annotate" aria-pressed="false">${browserIconSvg("Annotate")}</button>`;

export const viewerAnnotationLayer = `<div id="annotation-layer" aria-label="Annotation layer"><div id="annotation-hover"></div></div>`;

export const viewerAnnotationBubble = `<form id="annotation-bubble" role="dialog" aria-label="Annotation comment" hidden><input id="annotation-comment" autocomplete="off" spellcheck="true" maxlength="4000" placeholder="Add a comment…" aria-label="Annotation comment"><button id="annotation-action" type="button" data-mode="mic" aria-label="Start voice input"></button></form>`;

export const viewerAnnotation = String.raw`
const annotateToggle=document.querySelector('#annotate-toggle'),annotationLayer=document.querySelector('#annotation-layer'),annotationHover=document.querySelector('#annotation-hover'),annotationBubble=document.querySelector('#annotation-bubble'),annotationComment=document.querySelector('#annotation-comment'),annotationAction=document.querySelector('#annotation-action');
const annotationIcons={mic:${JSON.stringify(browserIconSvg("Mic"))},send:${JSON.stringify(browserIconSvg("Send"))},recording:${JSON.stringify(browserIconSvg("Stop"))},busy:${JSON.stringify(browserIconSvg("Loading"))}};
const annotationShortcut=/Mac|iPhone|iPad/.test(navigator.platform)?'⌘.':'Ctrl+.';
annotateToggle.dataset.tooltip='Annotate ('+annotationShortcut+')';
let annotating=false,annotationItems=[],annotationRects=[],annotationDraft=null,annotationHoverBusy=false,annotationHoverNext=null,annotationRectsTimer=0,annotationVoice=false,annotationRecorder=null,annotationBusy=false;
void json('./annotation-voice').then(r=>{annotationVoice=!!r.enabled;renderAnnotationAction();}).catch(()=>{});
function annotationScale(){const r=browserSurface.getBoundingClientRect();return{r,sx:r.width/vw,sy:r.height/vh};}
function placeBox(node,rect){const {sx,sy}=annotationScale();node.style.left=rect.x*sx+'px';node.style.top=rect.y*sy+'px';node.style.width=Math.max(0,rect.width*sx)+'px';node.style.height=Math.max(0,rect.height*sy)+'px';}
function showHover(rect,selected=false){if(!rect){annotationHover.dataset.active='false';return;}placeBox(annotationHover,rect);annotationHover.dataset.active='true';annotationHover.dataset.selected=String(selected);}
function renderMarkers(){for(const node of annotationLayer.querySelectorAll('.annotation-marker'))node.remove();annotationItems.forEach((item,index)=>{const rect=annotationRects[index]??item.rect;const marker=document.createElement('button');marker.type='button';marker.className='annotation-marker';marker.textContent=String(index+1);marker.title=item.comment||item.label;marker.dataset.editing=String(annotationDraft?.annotationId===item.id);if(!rect)marker.hidden=true;else{const {sx,sy}=annotationScale();marker.style.left=(rect.x+rect.width*item.anchor.x)*sx+'px';marker.style.top=(rect.y+rect.height*item.anchor.y)*sy+'px';}marker.addEventListener('pointerdown',e=>e.stopPropagation());marker.addEventListener('click',e=>{e.stopPropagation();editAnnotation(item,rect);});annotationLayer.append(marker);});}
async function refreshAnnotationRects(){if(!annotating||!annotationItems.length)return;try{const r=await json('./annotation-rects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,selectors:annotationItems.map(item=>item.selector)})});annotationRects=r.rects;renderMarkers();if(annotationDraft?.annotationId){const index=annotationItems.findIndex(item=>item.id===annotationDraft.annotationId);if(annotationRects[index])showHover(annotationRects[index],true);}}catch{}}
async function loadAnnotations(){try{const r=await json('./annotations?id='+encodeURIComponent(id));annotationItems=r.annotations;annotationRects=[];renderMarkers();void refreshAnnotationRects();}catch(e){status.textContent=e.message;}}
function setAnnotating(next){if(annotating===next)return;annotating=next;viewport.dataset.annotating=String(next);annotateToggle.setAttribute('aria-pressed',String(next));annotateToggle.dataset.tooltip=next?'Stop annotating ('+annotationShortcut+')':'Annotate ('+annotationShortcut+')';clearInterval(annotationRectsTimer);if(next){hideTooltip?.();void loadAnnotations();annotationRectsTimer=setInterval(refreshAnnotationRects,600);status.textContent='Click an element to annotate';}else{closeAnnotationBubble();showHover(null);for(const node of annotationLayer.querySelectorAll('.annotation-marker'))node.remove();status.textContent='Live';}}
annotateToggle.onclick=()=>setAnnotating(!annotating);
window.addEventListener('keydown',e=>{if(e.key==='.'&&(e.metaKey||e.ctrlKey)&&!e.altKey){e.preventDefault();e.stopImmediatePropagation();setAnnotating(!annotating);return;}if(annotating&&e.key==='Escape'&&e.target!==annotationComment){e.preventDefault();e.stopImmediatePropagation();if(annotationDraft)closeAnnotationBubble();else setAnnotating(false);}},true);
function queueHover(p){annotationHoverNext=p;if(annotationHoverBusy)return;annotationHoverBusy=true;(async()=>{while(annotationHoverNext){const next=annotationHoverNext;annotationHoverNext=null;try{const r=await json('./annotation-target',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,...next})});if(annotating&&!annotationDraft)showHover(r.target?.rect);}catch{if(!annotationDraft)showHover(null);}}annotationHoverBusy=false;})();}
annotationLayer.addEventListener('pointermove',e=>{if(!annotationDraft)queueHover(point(e));});
annotationLayer.addEventListener('pointerleave',()=>{if(!annotationDraft){annotationHoverNext=null;showHover(null);}});
annotationLayer.addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0)return;e.preventDefault();if(annotationDraft){closeAnnotationBubble();return;}const p=point(e);annotationDraft={point:p};void (async()=>{try{const r=await json('./annotation-target',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,...p})});if(annotationDraft?.point!==p)return;if(!r.target){annotationDraft=null;status.textContent='No element there';return;}annotationDraft.rect=r.target.rect;showHover(r.target.rect,true);openAnnotationBubble(r.target.rect,'');}catch(err){annotationDraft=null;status.textContent=err.message;}})();});
annotationLayer.addEventListener('wheel',e=>{e.preventDefault();const unit=e.deltaMode===1?16:e.deltaMode===2?vh:1;const event={kind:'wheel',...point(e),deltaX:Math.max(-3000,Math.min(3000,e.deltaX*unit)),deltaY:Math.max(-3000,Math.min(3000,e.deltaY*unit)),modifiers:0};withToolbarControl(()=>direct(event));if(annotationDraft)closeAnnotationBubble();showHover(null);setTimeout(refreshAnnotationRects,150);},{passive:false});
annotationLayer.addEventListener('contextmenu',e=>e.preventDefault());
function editAnnotation(item,rect){annotationDraft={annotationId:item.id,rect};if(rect)showHover(rect,true);openAnnotationBubble(rect??item.rect,item.comment);renderMarkers();}
function openAnnotationBubble(rect,text){const {r,sx,sy}=annotationScale();annotationComment.value=text;annotationBubble.hidden=false;const width=annotationBubble.offsetWidth,height=annotationBubble.offsetHeight;const left=Math.max(8,Math.min(innerWidth-width-8,r.left+(rect.x+rect.width/2)*sx-width/2));let top=r.top+(rect.y+rect.height)*sy+8;if(top+height>innerHeight-8)top=Math.max(8,r.top+rect.y*sy-height-8);annotationBubble.style.left=left+'px';annotationBubble.style.top=top+'px';annotationComment.placeholder=annotationDraft?.annotationId?'Edit comment (empty deletes)':'Add a comment…';renderAnnotationAction();annotationComment.focus({preventScroll:true});annotationComment.select();}
function closeAnnotationBubble(){stopAnnotationRecording(true);annotationDraft=null;annotationBubble.hidden=true;annotationComment.value='';showHover(null);if(annotating)renderMarkers();}
function renderAnnotationAction(){const text=annotationComment.value.trim();const editing=!!annotationDraft?.annotationId;const mode=annotationBusy?'busy':annotationRecorder?'recording':text||!annotationVoice||editing?'send':'mic';annotationAction.dataset.mode=mode;annotationAction.innerHTML=annotationIcons[mode];annotationAction.disabled=annotationBusy||(mode==='send'&&!text&&!editing&&annotationVoice);annotationAction.setAttribute('aria-label',mode==='mic'?'Start voice input':mode==='recording'?'Stop voice input':mode==='busy'?'Working…':editing&&!text?'Delete annotation':'Add annotation');}
annotationComment.addEventListener('input',renderAnnotationAction);
annotationComment.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();closeAnnotationBubble();}else if(e.key==='Enter'&&!e.isComposing){e.preventDefault();void submitAnnotation();}});
annotationBubble.addEventListener('pointerdown',e=>e.stopPropagation());
annotationBubble.addEventListener('submit',e=>{e.preventDefault();void submitAnnotation();});
annotationAction.addEventListener('click',()=>{const mode=annotationAction.dataset.mode;if(mode==='mic')void startAnnotationRecording();else if(mode==='recording')stopAnnotationRecording(false);else if(mode==='send')void submitAnnotation();});
async function submitAnnotation(){const draft=annotationDraft;if(!draft||annotationBusy)return;const comment=annotationComment.value.trim();annotationBusy=true;renderAnnotationAction();try{if(draft.annotationId){if(comment){const r=await json('./annotation-update',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,annotationId:draft.annotationId,comment})});annotationItems=annotationItems.map(item=>item.id===r.annotation.id?r.annotation:item);}else{await json('./annotation-delete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,annotationId:draft.annotationId})});const index=annotationItems.findIndex(item=>item.id===draft.annotationId);annotationItems.splice(index,1);annotationRects.splice(index,1);status.textContent='Annotation deleted';}}else{if(!comment)return;const r=await json('./annotations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,...draft.point,comment})});annotationItems.push(r.annotation);annotationRects.push(r.annotation.rect);if(parent!==window)parent.postMessage({type:'browse-annotation',annotation:{id:r.annotation.id,label:r.annotation.label}},location.origin);status.textContent='Annotation added to chat';}annotationBusy=false;closeAnnotationBubble();}catch(e){status.textContent=e.message;}finally{annotationBusy=false;renderAnnotationAction();}}
async function startAnnotationRecording(){if(annotationRecorder||annotationBusy)return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const recorder=new MediaRecorder(stream);const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=async()=>{for(const track of stream.getTracks())track.stop();if(recorder.discarded||!chunks.length)return;annotationBusy=true;renderAnnotationAction();try{const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});const bytes=new Uint8Array(await blob.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const r=await json('./annotation-transcribe',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,type:blob.type,audio:btoa(binary)})});if(r.text&&annotationDraft){annotationComment.value=(annotationComment.value.trim()+' '+r.text).trim();annotationComment.focus({preventScroll:true});}}catch(e){status.textContent=e.message;}finally{annotationBusy=false;renderAnnotationAction();}};annotationRecorder=recorder;recorder.start();setTimeout(()=>{if(annotationRecorder===recorder)stopAnnotationRecording(false);},120000);renderAnnotationAction();}catch(e){status.textContent=e?.name==='NotAllowedError'?'Microphone access was blocked':e.message;annotationRecorder=null;renderAnnotationAction();}}
function stopAnnotationRecording(discard){const recorder=annotationRecorder;if(!recorder)return;annotationRecorder=null;recorder.discarded=discard;if(recorder.state!=='inactive')recorder.stop();renderAnnotationAction();}
new ResizeObserver(()=>{if(annotating){renderMarkers();if(annotationDraft?.rect)showHover(annotationDraft.rect,true);}}).observe(browserSurface);
addEventListener('pagehide',()=>{clearInterval(annotationRectsTimer);stopAnnotationRecording(true);},{once:true});
`;
