import { browserIconSvg } from "./browser-icons";

// Page strings only ever reach textContent, value, or the BB composer through postMessage.
// The comment popover mirrors the responsive toolbar; voice mode mirrors BB's composer recorder.
export const viewerAnnotationCss = String.raw`
#annotation-layer{position:absolute;inset:0;z-index:5;display:none;cursor:crosshair;touch-action:none}
#viewport[data-annotating="true"] #annotation-layer{display:block}
#viewport[data-annotating="true"] #control-overlay{display:none}
#annotation-hover{position:absolute;display:none;border:1.5px solid var(--annotation,#3b82f6);border-radius:2px;background:color-mix(in srgb,var(--annotation,#3b82f6) 10%,transparent);pointer-events:none}
#annotation-hover[data-active="true"]{display:block}
#annotation-hover[data-selected="true"]{border-width:2px;background:color-mix(in srgb,var(--annotation,#3b82f6) 16%,transparent)}
.annotation-marker{position:absolute;width:22px;height:22px;margin:-11px 0 0 -11px;display:grid;place-items:center;border:2px solid #fff;border-radius:50% 50% 50% 4px;background:var(--annotation,#3b82f6);color:#fff;font:600 11px/1 system-ui,sans-serif;box-shadow:0 1px 4px #0006;cursor:pointer;padding:0}
.annotation-marker[hidden]{display:none}
.annotation-marker:hover,.annotation-marker[data-editing="true"]{transform:scale(1.12)}
#annotation-bubble{position:fixed;z-index:20;display:flex;align-items:center;gap:2px;width:min(320px,calc(100vw - 16px));height:38px;margin:0;padding:4px 4px 4px 10px;border:1px solid var(--border,#ffffff18);border-radius:6px;background:var(--popover,#18181b);color:var(--popover-foreground,#e4e4e7);box-shadow:0 1px 2px #0003}
#annotation-bubble[hidden]{display:none}
#annotation-bubble[data-voice]{padding-left:4px;gap:6px}
#annotation-bubble[data-voice] #annotation-comment,#annotation-bubble[data-voice] #annotation-action{display:none}
#annotation-bubble:not([data-voice]) .annotation-voice{display:none}
#annotation-comment{flex:1;min-width:0;height:28px;margin:0;padding:0;border:0;border-radius:0;outline:0;background:transparent;color:inherit;font:inherit;font-size:12px;box-shadow:none}
#annotation-comment:hover,#annotation-comment:focus{background:transparent}
#annotation-comment::placeholder{color:var(--muted-foreground,#a1a1aa)}
#annotation-bubble button{flex:none;width:28px;height:28px;margin:0;padding:0;border-radius:4px;display:inline-flex;align-items:center;justify-content:center}
#annotation-bubble button svg{width:14px;height:14px}
#annotation-bubble button:disabled{opacity:.5;pointer-events:none}
#annotation-bubble button:focus-visible{outline:1px solid var(--ring,#71717a);outline-offset:1px}
#annotation-bubble .annotation-primary{background:var(--primary,#fafafa);color:var(--primary-foreground,#0b0b0d)}
#annotation-bubble .annotation-primary:hover{background:color-mix(in srgb,var(--primary,#fafafa) 90%,var(--foreground,#fafafa));color:var(--primary-foreground,#0b0b0d)}
#annotation-bubble .annotation-ghost{background:transparent;color:var(--popover-foreground,#e4e4e7)}
#annotation-bubble .annotation-ghost:hover{background:var(--state-hover,#ffffff0c);color:var(--foreground,#fafafa)}
#annotation-bubble [data-busy] svg{animation:spin 1s linear infinite}
#annotation-waveform{flex:1;min-width:0;height:20px;display:block;color:var(--foreground,#fafafa)}
#annotation-bubble[data-voice="transcribing"] #annotation-waveform{opacity:.5}
`;

export const viewerAnnotationToolbarButton = `<button id="annotate-toggle" title="Annotate" aria-label="Annotate" aria-pressed="false">${browserIconSvg("Annotate")}</button>`;

export const viewerAnnotationLayer = `<div id="annotation-layer" aria-label="Annotation layer"><div id="annotation-hover"></div></div>`;

export const viewerAnnotationBubble = `<form id="annotation-bubble" role="dialog" aria-label="Annotation comment" hidden><input id="annotation-comment" autocomplete="off" spellcheck="true" maxlength="4000" placeholder="Add a comment…" aria-label="Annotation comment"><button id="annotation-action" class="annotation-primary" type="button" aria-label="Start voice input"></button><button id="annotation-voice-cancel" class="annotation-voice annotation-ghost" type="button" aria-label="Cancel recording">${browserIconSvg("Close")}</button><canvas id="annotation-waveform" class="annotation-voice" aria-hidden="true"></canvas><span id="annotation-voice-status" class="annotation-voice sr-only" aria-live="polite"></span><button id="annotation-voice-confirm" class="annotation-voice annotation-primary" type="button" aria-label="Stop and transcribe recording">${browserIconSvg("Check")}</button></form>`;

export const viewerAnnotation = String.raw`
const annotateToggle=document.querySelector('#annotate-toggle'),annotationLayer=document.querySelector('#annotation-layer'),annotationHover=document.querySelector('#annotation-hover'),annotationBubble=document.querySelector('#annotation-bubble'),annotationComment=document.querySelector('#annotation-comment'),annotationAction=document.querySelector('#annotation-action'),annotationVoiceCancel=document.querySelector('#annotation-voice-cancel'),annotationVoiceConfirm=document.querySelector('#annotation-voice-confirm'),annotationVoiceStatus=document.querySelector('#annotation-voice-status'),annotationWaveform=document.querySelector('#annotation-waveform');
const annotationIcons={mic:${JSON.stringify(browserIconSvg("Mic"))},send:${JSON.stringify(browserIconSvg("Send"))},check:${JSON.stringify(browserIconSvg("Check"))},busy:${JSON.stringify(browserIconSvg("Loading"))}};
const annotationShortcut=/Mac|iPhone|iPad/.test(navigator.platform)?'⌘.':'Ctrl+.';
annotateToggle.dataset.tooltip='Annotate ('+annotationShortcut+')';
let annotating=false,annotationItems=[],annotationRects=[],annotationDraft=null,annotationHoverBusy=false,annotationHoverNext=null,annotationRectsTimer=0,annotationVoice=false,annotationBusy=false,annotationVoiceSession=null,annotationViewKey='';
void json('./annotation-voice').then(r=>{annotationVoice=!!r.enabled;renderAnnotationAction();}).catch(()=>{});
const post=(url,body,signal)=>json(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal});
function annotationScale(){const r=browserSurface.getBoundingClientRect();return{r,sx:r.width/vw,sy:r.height/vh};}
function placeBox(node,rect){const {sx,sy}=annotationScale();node.style.left=rect.x*sx+'px';node.style.top=rect.y*sy+'px';node.style.width=Math.max(0,rect.width*sx)+'px';node.style.height=Math.max(0,rect.height*sy)+'px';}
function showHover(rect,selected=false){if(!rect){annotationHover.dataset.active='false';return;}placeBox(annotationHover,rect);annotationHover.dataset.active='true';annotationHover.dataset.selected=String(selected);}
function renderMarkers(){for(const node of annotationLayer.querySelectorAll('.annotation-marker'))node.remove();annotationItems.forEach((item,index)=>{const rect=annotationRects[index]??item.rect;const marker=document.createElement('button');marker.type='button';marker.className='annotation-marker';marker.textContent=String(index+1);marker.title=item.comment||item.label;marker.dataset.editing=String(annotationDraft?.annotationId===item.id);if(!rect)marker.hidden=true;else{const {sx,sy}=annotationScale();marker.style.left=(rect.x+rect.width*item.anchor.x)*sx+'px';marker.style.top=(rect.y+rect.height*item.anchor.y)*sy+'px';}marker.addEventListener('pointerdown',e=>e.stopPropagation());marker.addEventListener('click',e=>{e.stopPropagation();editAnnotation(item,rect);});annotationLayer.append(marker);});}
async function refreshAnnotationRects(){if(!annotating||!annotationItems.length)return;try{const r=await post('./annotation-rects',{id,selectors:annotationItems.map(item=>item.selector)});annotationRects=r.rects;renderMarkers();if(annotationDraft?.annotationId){const index=annotationItems.findIndex(item=>item.id===annotationDraft.annotationId);if(annotationRects[index])showHover(annotationRects[index],true);}}catch{}}
async function loadAnnotations(){try{const r=await json('./annotations?id='+encodeURIComponent(id));annotationItems=r.annotations;annotationRects=[];renderMarkers();void refreshAnnotationRects();}catch(e){status.textContent=e.message;}}
function setAnnotating(next){if(annotating===next)return;annotating=next;viewport.dataset.annotating=String(next);annotateToggle.setAttribute('aria-pressed',String(next));annotateToggle.dataset.tooltip=next?'Stop annotating ('+annotationShortcut+')':'Annotate ('+annotationShortcut+')';clearInterval(annotationRectsTimer);if(next){hideTooltip?.();annotationViewKey=vw+'x'+vh+' '+currentUrl;void loadAnnotations();annotationRectsTimer=setInterval(refreshAnnotationRects,600);status.textContent='Click an element to annotate';}else{closeAnnotationBubble();showHover(null);for(const node of annotationLayer.querySelectorAll('.annotation-marker'))node.remove();status.textContent='Live';}}
annotateToggle.onclick=()=>setAnnotating(!annotating);
// A pick belongs to one layout and page. Unsaved picks are dropped when either changes.
function onAnnotationViewChange(){const key=vw+'x'+vh+' '+currentUrl;if(key===annotationViewKey)return;annotationViewKey=key;if(!annotating)return;annotationHoverNext=null;if(annotationDraft)closeAnnotationBubble();else showHover(null);annotationRects=[];void refreshAnnotationRects();}
function onAnnotationViewportPending(){if(annotating&&annotationDraft)closeAnnotationBubble();}
window.addEventListener('keydown',e=>{if(e.key==='.'&&(e.metaKey||e.ctrlKey)&&!e.altKey){e.preventDefault();e.stopImmediatePropagation();setAnnotating(!annotating);return;}if(annotating&&e.key==='Escape'&&e.target!==annotationComment){e.preventDefault();e.stopImmediatePropagation();if(annotationVoiceSession)cancelAnnotationVoice();else if(annotationDraft)closeAnnotationBubble();else setAnnotating(false);}},true);
function queueHover(p){annotationHoverNext=p;if(annotationHoverBusy)return;annotationHoverBusy=true;(async()=>{while(annotationHoverNext){const next=annotationHoverNext;annotationHoverNext=null;try{const r=await post('./annotation-target',{id,...next});if(annotating&&!annotationDraft)showHover(r.target?.rect);}catch{if(!annotationDraft)showHover(null);}}annotationHoverBusy=false;})();}
annotationLayer.addEventListener('pointermove',e=>{if(!annotationDraft)queueHover(point(e));});
annotationLayer.addEventListener('pointerleave',()=>{if(!annotationDraft){annotationHoverNext=null;showHover(null);}});
annotationLayer.addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0)return;e.preventDefault();if(annotationDraft){closeAnnotationBubble();return;}const p=point(e);const draft={point:p};annotationDraft=draft;void (async()=>{try{const r=await post('./annotation-target',{id,...p});if(annotationDraft!==draft)return;if(!r.target){annotationDraft=null;status.textContent='No element there';return;}draft.rect=r.target.rect;showHover(r.target.rect,true);openAnnotationBubble(r.target.rect,'');}catch(err){if(annotationDraft===draft)annotationDraft=null;status.textContent=err.message;}})();});
annotationLayer.addEventListener('wheel',e=>{e.preventDefault();const unit=e.deltaMode===1?16:e.deltaMode===2?vh:1;const event={kind:'wheel',...point(e),deltaX:Math.max(-3000,Math.min(3000,e.deltaX*unit)),deltaY:Math.max(-3000,Math.min(3000,e.deltaY*unit)),modifiers:0};withToolbarControl(()=>direct(event));if(annotationDraft)closeAnnotationBubble();showHover(null);setTimeout(refreshAnnotationRects,150);},{passive:false});
annotationLayer.addEventListener('contextmenu',e=>e.preventDefault());
function editAnnotation(item,rect){annotationDraft={annotationId:item.id,rect};if(rect)showHover(rect,true);openAnnotationBubble(rect??item.rect,item.comment);renderMarkers();}
function openAnnotationBubble(rect,text){const {r,sx,sy}=annotationScale();annotationComment.value=text;annotationBubble.hidden=false;const width=annotationBubble.offsetWidth,height=annotationBubble.offsetHeight;const left=Math.max(8,Math.min(innerWidth-width-8,r.left+(rect.x+rect.width/2)*sx-width/2));let top=r.top+(rect.y+rect.height)*sy+8;if(top+height>innerHeight-8)top=Math.max(8,r.top+rect.y*sy-height-8);annotationBubble.style.left=left+'px';annotationBubble.style.top=top+'px';annotationComment.placeholder=annotationDraft?.annotationId?'Edit comment (empty deletes)':'Add a comment…';renderAnnotationAction();annotationComment.focus({preventScroll:true});annotationComment.select();}
function closeAnnotationBubble(){cancelAnnotationVoice();annotationDraft=null;annotationBubble.hidden=true;annotationComment.value='';showHover(null);if(annotating)renderMarkers();}
function renderAnnotationAction(){const text=annotationComment.value.trim();const editing=!!annotationDraft?.annotationId;const mode=annotationBusy?'busy':text||!annotationVoice||editing?'send':'mic';if(annotationAction.dataset.mode!==mode){annotationAction.dataset.mode=mode;annotationAction.innerHTML=annotationIcons[mode];}annotationAction.toggleAttribute('data-busy',mode==='busy');annotationAction.disabled=annotationBusy||(mode==='send'&&!text&&!editing);annotationAction.setAttribute('aria-label',mode==='mic'?'Start voice input':mode==='busy'?'Working…':editing&&!text?'Delete annotation':'Add annotation');}
annotationComment.addEventListener('input',renderAnnotationAction);
annotationComment.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();closeAnnotationBubble();}else if(e.key==='Enter'&&!e.isComposing){e.preventDefault();void submitAnnotation();}});
annotationBubble.addEventListener('pointerdown',e=>e.stopPropagation());
annotationBubble.addEventListener('submit',e=>{e.preventDefault();void submitAnnotation();});
annotationAction.addEventListener('click',()=>{if(annotationAction.dataset.mode==='mic')void startAnnotationVoice();else if(annotationAction.dataset.mode==='send')void submitAnnotation();});
annotationVoiceCancel.addEventListener('click',()=>cancelAnnotationVoice());
annotationVoiceConfirm.addEventListener('click',()=>finishAnnotationVoice());
async function submitAnnotation(){const draft=annotationDraft;if(!draft||annotationBusy||annotationVoiceSession)return;const comment=annotationComment.value.trim();if(!draft.annotationId&&!comment)return;annotationBusy=true;renderAnnotationAction();try{if(draft.annotationId){if(comment){const r=await post('./annotation-update',{id,annotationId:draft.annotationId,comment});annotationItems=annotationItems.map(item=>item.id===r.annotation.id?r.annotation:item);}else{await post('./annotation-delete',{id,annotationId:draft.annotationId});const index=annotationItems.findIndex(item=>item.id===draft.annotationId);annotationItems.splice(index,1);annotationRects.splice(index,1);status.textContent='Annotation deleted';}}else{const r=await post('./annotations',{id,...draft.point,comment});annotationItems.push(r.annotation);annotationRects.push(r.annotation.rect);if(parent!==window)parent.postMessage({type:'browse-annotation',annotation:{id:r.annotation.id,label:r.annotation.label}},location.origin);status.textContent='Annotation added to chat';}annotationBusy=false;if(annotationDraft===draft)closeAnnotationBubble();}catch(e){status.textContent=e.message;}finally{annotationBusy=false;renderAnnotationAction();}}
function setAnnotationVoiceState(state){if(state)annotationBubble.dataset.voice=state;else delete annotationBubble.dataset.voice;const transcribing=state==='transcribing';annotationVoiceCancel.setAttribute('aria-label',transcribing?'Cancel transcription':'Cancel recording');annotationVoiceConfirm.setAttribute('aria-label',transcribing?'Transcribing voice input':'Stop and transcribe recording');annotationVoiceConfirm.disabled=transcribing;annotationVoiceConfirm.toggleAttribute('data-busy',transcribing);annotationVoiceConfirm.innerHTML=transcribing?annotationIcons.busy:annotationIcons.check;annotationVoiceStatus.textContent=transcribing?'Transcribing':state?'Recording':'';}
async function startAnnotationVoice(){if(annotationVoiceSession||annotationBusy||!annotationDraft)return;const session={draft:annotationDraft,chunks:[],cancelled:false};annotationVoiceSession=session;setAnnotationVoiceState('recording');annotationVoiceCancel.focus({preventScroll:true});try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(annotationVoiceSession!==session){for(const track of stream.getTracks())track.stop();return;}const type=['audio/webm','audio/mp4','audio/ogg'].find(value=>MediaRecorder.isTypeSupported(value));const recorder=new MediaRecorder(stream,type?{mimeType:type}:undefined);session.stream=stream;session.recorder=recorder;session.stopWave=drawAnnotationWaveform(stream);recorder.ondataavailable=e=>{if(e.data.size)session.chunks.push(e.data);};recorder.onstop=()=>{releaseAnnotationVoice(session);if(!session.cancelled)void transcribeAnnotationVoice(session,recorder.mimeType||type||'audio/webm');};recorder.start();session.timer=setTimeout(()=>{if(annotationVoiceSession===session)finishAnnotationVoice();},120000);}catch(e){releaseAnnotationVoice(session);if(annotationVoiceSession===session){annotationVoiceSession=null;setAnnotationVoiceState(null);annotationComment.focus({preventScroll:true});}status.textContent=e?.name==='NotAllowedError'?'Microphone permission was denied':e?.name==='NotFoundError'?'No microphone was found':e?.name==='NotReadableError'?'Microphone is already in use':e.message||'Failed to start voice recording';}}
function releaseAnnotationVoice(session){clearTimeout(session.timer);session.stopWave?.();session.stopWave=null;for(const track of session.stream?.getTracks()??[])track.stop();}
function finishAnnotationVoice(){const session=annotationVoiceSession;if(!session?.recorder||session.recorder.state==='inactive')return;setAnnotationVoiceState('transcribing');session.recorder.stop();}
function cancelAnnotationVoice(){const session=annotationVoiceSession;if(!session)return;session.cancelled=true;session.abort?.abort();annotationVoiceSession=null;if(session.recorder&&session.recorder.state!=='inactive')session.recorder.stop();else releaseAnnotationVoice(session);setAnnotationVoiceState(null);if(!annotationBubble.hidden)annotationComment.focus({preventScroll:true});}
async function transcribeAnnotationVoice(session,type){if(!session.chunks.length){if(annotationVoiceSession===session){annotationVoiceSession=null;setAnnotationVoiceState(null);}status.textContent='No audio was recorded';return;}session.abort=new AbortController();try{const blob=new Blob(session.chunks,{type});const bytes=new Uint8Array(await blob.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));const r=await post('./annotation-transcribe',{id,type:blob.type,audio:btoa(binary)},session.abort.signal);if(annotationVoiceSession!==session||annotationDraft!==session.draft)return;if(r.text)annotationComment.value=(annotationComment.value.trim()+' '+r.text).trim();}catch(e){if(!session.cancelled)status.textContent=e.message||'Voice input failed';}finally{if(annotationVoiceSession===session){annotationVoiceSession=null;setAnnotationVoiceState(null);renderAnnotationAction();annotationComment.focus({preventScroll:true});}}}
// Port of BB's composer waveform: RMS bars scrolling in from the right, faded at the left edge.
function drawAnnotationWaveform(stream){const canvas=annotationWaveform,context=canvas.getContext('2d');if(!context)return()=>{};const bar=3,step=bar+2,bars=[];let width=0,height=0,capacity=1,middle=0,amplitude=0,fade=0;const measure=()=>{const ratio=devicePixelRatio||1,box=canvas.getBoundingClientRect();width=box.width;height=box.height;canvas.width=Math.max(1,Math.round(width*ratio));canvas.height=Math.max(1,Math.round(height*ratio));context.setTransform(ratio,0,0,ratio,0,0);context.strokeStyle=getComputedStyle(canvas).color||'currentColor';context.lineCap='round';context.lineWidth=bar;middle=height/2;amplitude=Math.max(0,(height*.95-bar)/2);fade=width*.15;capacity=Math.max(1,Math.floor(width/step));if(bars.length>capacity)bars.splice(0,bars.length-capacity);};const draw=()=>{context.clearRect(0,0,width,height);for(let i=0;i<bars.length;i++){const level=bars[bars.length-1-i],x=width-bar/2-i*step;if(x+bar<0)break;const half=Math.max(.06,level)*amplitude;context.globalAlpha=x<fade?Math.max(.15,x/fade):1;context.beginPath();context.moveTo(x,middle-half);context.lineTo(x,middle+half);context.stroke();}context.globalAlpha=1;};measure();const track=stream.getAudioTracks()[0];if(!track||!window.AudioContext){draw();return()=>{};}const audio=new AudioContext();void audio.resume();const clone=track.clone(),source=audio.createMediaStreamSource(new MediaStream([clone])),analyser=audio.createAnalyser();analyser.fftSize=1024;source.connect(analyser);const samples=new Uint8Array(analyser.fftSize);let frame=0,raf=0;const tick=()=>{if(frame++%2===0){analyser.getByteTimeDomainData(samples);let sum=0;for(const value of samples){const n=(value-128)/128;sum+=n*n;}const level=Math.min(1,(Math.max(0,Math.sqrt(sum/samples.length)-.006)*8)**.6);bars.push(level);if(bars.length>capacity)bars.shift();draw();}raf=requestAnimationFrame(tick);};const resize=new ResizeObserver(()=>{measure();draw();});resize.observe(canvas);raf=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(raf);resize.disconnect();source.disconnect();analyser.disconnect();clone.stop();void audio.close();context.clearRect(0,0,width,height);};}
new ResizeObserver(()=>{if(annotating){renderMarkers();if(annotationDraft?.rect)showHover(annotationDraft.rect,true);}}).observe(browserSurface);
addEventListener('pagehide',()=>{clearInterval(annotationRectsTimer);cancelAnnotationVoice();},{once:true});
`;
