import { openClientExternal } from "./client-external";
import {viewerTrace} from "./viewer-trace";
import { videoClient } from "./video-client";
import { viewerInteraction } from "./viewer-interaction";
import { browserIconSvg } from "./browser-icons";
/** Static viewer: page strings only ever enter textContent or form values. */
export const viewerHtml = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Browse — live browser</title><style>
:root{color-scheme:dark;font:13px system-ui,sans-serif}*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0;overflow:hidden}body{display:flex;flex-direction:column;background:#0b0b0d;color:#d4d4d8}header{height:48px;flex:none;display:flex;gap:8px;padding:8px 16px;align-items:center;border-bottom:1px solid #ffffff12;background:#111113}button,summary{display:grid;place-items:center;width:28px;height:28px;border:0;border-radius:6px;background:transparent;color:#a1a1aa;cursor:pointer;flex:none}button:hover,summary:hover{background:#ffffff0c;color:#fafafa}button:focus-visible,summary:focus-visible,input:focus-visible{outline:2px solid #71717a;outline-offset:1px}svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}input{flex:1;min-width:0;height:32px;margin:0 5px;padding:0 10px;border:1px solid transparent;border-radius:6px;background:#ffffff05;color:#e4e4e7;font:inherit}input:focus{background:#ffffff09}input::placeholder{color:#71717a}main{position:relative;display:grid;place-items:center;flex:1;min-height:0;min-width:0;overflow:hidden;padding:0}#screen{display:block;flex:none;outline-offset:2px;outline:1px solid var(--border,#ffffff12);outline-offset:0;border-radius:6px}#screen{touch-action:none;user-select:none}#screen:not([data-frame]){visibility:hidden}#browser-keyboard{position:fixed;left:0;bottom:0;width:1px;height:1px;opacity:0;resize:none;padding:0;border:0;pointer-events:none}#status,#machine{position:absolute;bottom:8px;max-width:calc(50% - 20px);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;padding:4px 8px;border-radius:5px;background:#111113dd;color:#a1a1aa;font-size:11px;pointer-events:none}#status{left:14px}#machine{right:14px}details{position:relative}summary{list-style:none}summary::-webkit-details-marker{display:none}#identity{padding:8px;color:#a1a1aa;overflow-wrap:anywhere;font-size:12px;line-height:1.6}@media(max-width:420px){main{padding:0}input{margin:0 2px;padding:0 6px}}

body{background:var(--sidebar,var(--background,#0b0b0d));color:var(--sidebar-foreground,var(--foreground,#d4d4d8))}header{background:var(--sidebar,var(--background,#111113));border-color:var(--sidebar-border,var(--border,#ffffff12))}button,summary{color:var(--muted-foreground,#a1a1aa)}button:hover,summary:hover{background:var(--state-hover,#ffffff0c);color:var(--foreground,#fafafa)}button:disabled{cursor:default;opacity:.45}button:disabled:hover{background:transparent;color:var(--muted-foreground,#a1a1aa)}input{margin:0;border:0;background:transparent;color:var(--foreground,#e4e4e7)}input:focus{background:transparent}.toolbar-group{display:flex;align-items:center;gap:4px;flex:none}.toolbar-group[aria-label="Page actions"]{width:92px}.address-field{height:28px;display:flex;align-items:center;gap:4px;flex:1;min-width:0;margin:0;border:0;box-shadow:inset 0 0 0 1px var(--input,var(--border,#ffffff18));background:transparent;border-radius:6px}.address-field input{height:28px;font-size:12px;padding:4px 12px}.address-field input:focus-visible{outline:none}.address-field button{width:28px;height:28px;margin-right:2px}input::placeholder{color:var(--muted-foreground,#71717a)}details[open]>summary{background:var(--state-active,var(--state-hover,#ffffff0c));color:var(--foreground,#fafafa)}.menu{position:absolute;z-index:20;right:0;top:32px;width:184px;max-width:calc(100vw - 24px);padding:4px;overflow:hidden;border:1px solid var(--border,#ffffff18);border-radius:6px;background:var(--popover,#18181b);color:var(--popover-foreground,#e4e4e7);box-shadow:0 4px 12px #0005}.menu button{width:100%;height:28px;display:flex;align-items:center;justify-content:flex-start;gap:8px;padding:0 8px;border-radius:4px;color:inherit;font:inherit;font-size:12px;font-weight:400;text-align:left}.menu button:hover,.menu button:focus-visible{outline:none;background:var(--state-hover,#ffffff0c);color:var(--foreground,#fafafa)}.menu button svg{width:16px;height:16px;flex:none;color:var(--muted-foreground,#a1a1aa)}.separator{height:1px;background:var(--border,#ffffff18);margin:4px -4px}#identity{font-size:11px;color:var(--muted-foreground,#a1a1aa)}#status,#machine{background:var(--popover,#111113dd);color:var(--muted-foreground,#a1a1aa)}

#status{pointer-events:auto}#status,#machine{display:flex;align-items:center;gap:6px}#machine svg{width:13px;height:13px;flex:none}#machine-label{overflow:hidden;text-overflow:ellipsis}.status-dot{width:6px;height:6px;border-radius:50%;flex:none;background:var(--warning,#eab308)}#status[data-state=ready] .status-dot{background:var(--success,#22c55e)}#status[data-state=error] .status-dot{background:var(--destructive,#ef4444)}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
#action-tooltip{position:fixed;z-index:100;max-width:calc(100vw - 16px);padding:6px 12px;border-radius:6px;border:1px solid var(--border,#ffffff18);background:var(--popover,#18181b);color:var(--popover-foreground,#e4e4e7);box-shadow:0 4px 12px #0003;font-size:12px;line-height:16px;pointer-events:none}#action-tooltip[hidden]{display:none}
@keyframes spin{to{transform:rotate(360deg)}}/* Keep the check and spinner at 16px; slightly reduce the denser copy glyph. */#copy-url svg{width:16px;height:16px}#copy-url[data-state=idle] svg{width:15px;height:15px}#copy-url[data-state=copied] svg{width:16px;height:16px}#copy-url[data-state=loading] svg{animation:spin 1s linear infinite}#copy-url:disabled{cursor:default;opacity:1}#copy-url,#copy-url:hover,#copy-url:active,#copy-url:focus-visible{background:transparent}#copy-url:hover,#copy-url[data-state=copied]{color:#fff}
#viewport:not([data-loaded="true"]) #status,#viewport:not([data-loaded="true"]) #machine{visibility:hidden}#browser-surface,#viewport-skeleton{grid-area:1/1}#browser-surface{position:relative;display:grid;place-items:center;overflow:hidden;border-radius:6px}#screen,#control-overlay{grid-area:1/1;width:100%;height:100%}#viewport-skeleton{width:min(100%,1280px);max-height:100%;aspect-ratio:8/5;border:1px solid var(--border,#ffffff12);border-radius:6px;background:var(--muted,#ffffff08);pointer-events:none}#viewport-skeleton[hidden]{display:none}@media(prefers-reduced-motion:no-preference){#viewport-skeleton{animation:skeleton-pulse 1.8s ease-in-out infinite}}@keyframes skeleton-pulse{50%{opacity:.45}}
#control-overlay{z-index:4;display:flex;align-items:center;justify-content:center;background:#0006;opacity:0;visibility:hidden;pointer-events:none}#browser-surface:hover #control-overlay,#browser-surface:focus-within #control-overlay,#viewport[data-control="taking"] #control-overlay{opacity:1;visibility:visible;pointer-events:auto}#viewport[data-control="human"] #control-overlay{display:none}#control-toggle{width:auto;height:32px;padding:0 12px;display:inline-flex;align-items:center;justify-content:center;gap:8px;white-space:nowrap;border:0;border-radius:6px;background:var(--foreground,#fafafa);color:var(--background,#0b0b0d);font:inherit;font-size:12px;font-weight:500}#control-toggle:hover{background:color-mix(in srgb,var(--foreground,#fafafa) 90%,transparent);color:var(--background,#0b0b0d)}#control-toggle:focus-visible{outline:none;box-shadow:0 0 0 1px var(--ring,#a1a1aa)}#control-toggle:disabled{pointer-events:none;opacity:.5}#control-toggle svg{width:16px;height:16px;pointer-events:none;flex:none}.control-icon{display:inline-flex}.control-icon[hidden]{display:none}.control-icon[data-kind="loading"] svg{animation:spin 1s linear infinite}#viewport:not([data-loaded="true"]) #control-overlay{visibility:hidden}
#responsive-toggle[aria-pressed="true"]{background:var(--state-active,var(--state-hover,#ffffff0c));color:var(--foreground,#fafafa)}#responsive-toggle[data-pending="true"]{background:var(--state-hover,#ffffff0c);color:var(--foreground,#fafafa)}#responsive-toggle[data-pending="true"] svg{animation:spin 1s linear infinite}#viewport[data-responsive="true"]{padding-bottom:58px}#responsive-controls{position:absolute;z-index:7;left:50%;bottom:10px;transform:translateX(-50%);height:38px;display:flex;align-items:center;gap:2px;padding:4px;border:1px solid var(--border,#ffffff18);border-radius:6px;background:var(--popover,#18181b);color:var(--popover-foreground,#e4e4e7);box-shadow:0 1px 2px #0003;white-space:nowrap}#responsive-controls[hidden]{display:none}#responsive-controls button{height:28px;width:28px;border-radius:4px}#responsive-controls button:hover{background:var(--state-hover,#ffffff0c);color:var(--foreground,#fafafa)}.device-select{position:relative;display:flex;align-items:center}.device-select>svg{position:absolute;right:6px;width:14px;height:14px;color:var(--muted-foreground,#a1a1aa);pointer-events:none;opacity:.6}#device-preset{appearance:none;height:28px;max-width:150px;border:0;border-radius:4px;padding:0 24px 0 8px;background:transparent;color:inherit;font:inherit;font-size:12px;outline:none}#device-preset:hover,#device-preset:focus-visible{background:var(--state-hover,#ffffff0c);color:var(--foreground,#fafafa)}.responsive-size{display:flex;align-items:center;gap:2px;color:var(--muted-foreground,#a1a1aa)}.responsive-size input{width:46px;height:28px;flex:none;margin:0;padding:0 4px;border-radius:4px;text-align:center;font-size:12px;color:var(--popover-foreground,#e4e4e7);box-shadow:none}.responsive-size input:hover,.responsive-size input:focus{background:var(--state-hover,#ffffff0c);color:var(--foreground,#fafafa)}.responsive-size input:focus-visible{outline:1px solid var(--ring,#71717a);outline-offset:0}.responsive-divider{width:1px;height:16px;background:var(--border,#ffffff18);margin:0 2px}
@media(max-width:520px){#status,#machine{display:none}}
#dialog-overlay{position:absolute;z-index:9;inset:0;display:grid;place-items:center;padding:16px;background:#0008}#dialog-overlay[hidden]{display:none}.browser-dialog{width:min(360px,100%);padding:16px;border:1px solid var(--border,#ffffff18);border-radius:8px;background:var(--popover,#18181b);color:var(--popover-foreground,#e4e4e7);box-shadow:0 12px 36px #0008}.browser-dialog p{margin:0;white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px;line-height:1.45}.browser-dialog input{width:100%;height:32px;margin:12px 0 0;padding:0 8px;border:1px solid var(--input,var(--border,#ffffff18));border-radius:6px;background:transparent}.dialog-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.dialog-actions button{width:auto;height:28px;padding:0 10px;border:1px solid var(--border,#ffffff18);background:transparent;color:inherit;font:inherit}.dialog-actions button:last-child{background:var(--foreground,#fafafa);color:var(--background,#0b0b0d)}
main[data-devtools="true"]{display:flex;align-items:stretch;gap:0;padding:0}#page-pane{position:relative;display:grid;place-items:center;flex:1;min-width:0;min-height:0;overflow:hidden;padding:12px;align-self:stretch;justify-self:stretch}@media(max-width:420px){#page-pane{padding:6px}}#devtools-divider{flex:none;width:10px;margin:0 -2px;cursor:col-resize;touch-action:none;position:relative;z-index:8}#devtools-divider::after{content:"";position:absolute;inset:0 4px 0 3px;border-radius:3px}#devtools-divider:hover::after{background:var(--state-hover,#ffffff14)}#devtools-divider[hidden]{display:none}#devtools-wrap{flex:none;display:flex;flex-direction:column;min-width:0;border-left:1px solid var(--border,#ffffff12);background:var(--sidebar,var(--background,#0b0b0d))}#devtools-wrap[hidden]{display:none}#devtools-header{flex:none;display:flex;align-items:center;gap:8px;height:36px;padding:0 8px 0 12px;border-bottom:1px solid var(--border,#ffffff12);font-size:12px;color:var(--muted-foreground,#a1a1aa)}#devtools-header span{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#devtools-status{flex:1;display:grid;place-items:center;padding:16px;font-size:12px;color:var(--muted-foreground,#a1a1aa)}#devtools-status:empty{display:none}#devtools-frame{flex:1;min-height:0;width:100%;border:0;background:transparent;color-scheme:light dark}@media(max-width:700px){main[data-devtools="true"]{flex-direction:column}#devtools-divider{display:none}#devtools-wrap{border-left:0;border-top:1px solid var(--border,#ffffff12);min-height:280px}}
</style></head><body>
<header aria-label="Browser navigation">
<div class="toolbar-group" role="group" aria-label="Navigation">
<button id="back" title="Back" aria-label="Back">${browserIconSvg("ArrowLeft")} </button>
<button id="forward" title="Forward" aria-label="Forward">${browserIconSvg("ArrowRight")} </button>
<button id="reload" title="Reload" aria-label="Reload">${browserIconSvg("RefreshCw")} </button>
</div>
<div class="address-field" role="group" aria-label="Address"><input id="url" aria-label="Page address" placeholder="Enter URL" spellcheck="false" autocapitalize="off"><button id="copy-url" title="Copy current URL" aria-label="Copy current URL">${browserIconSvg("Copy")}</button></div>
<div class="toolbar-group" role="group" aria-label="Page actions"><button id="responsive-toggle" title="Responsive mode" aria-label="Responsive mode" aria-pressed="false" disabled>${browserIconSvg("Responsive")}</button><button id="open-external" title="Open externally" aria-label="Open externally">${browserIconSvg("External")}</button><details><summary title="More options" aria-label="More options">${browserIconSvg("More")}</summary><div class="menu" role="menu" aria-label="More options"><button role="menuitem" data-maintenance="hard-reload">${browserIconSvg("RefreshCw")}<span>Hard reload</span></button><button role="menuitem" data-maintenance="open-devtools">${browserIconSvg("Terminal")}<span>Open DevTools</span></button><div class="separator" role="separator"></div><button role="menuitem" data-maintenance="clear-cookies" title="Signs you out of websites in this session profile">${browserIconSvg("Cookie")}<span>Clear cookies</span></button><button role="menuitem" data-maintenance="clear-cache">${browserIconSvg("Clean")}<span>Clear cache</span></button><div class="separator" role="separator"></div><button role="menuitem" id="copy-session">${browserIconSvg("Copy")}<span>Copy session ID</span></button></div></details></div>
</header>
<main id="viewport" data-control="agent" data-devtools="false"><div id="page-pane"><div id="viewport-skeleton" role="status" aria-label="Loading page"></div><div id="browser-surface"><canvas id="screen" tabindex="0" aria-label="Live browser view"></canvas><div id="control-overlay"><button id="control-toggle" type="button"><span class="control-icon" data-kind="cursor">${browserIconSvg("Cursor")}</span><span class="control-icon" data-kind="loading" hidden>${browserIconSvg("Loading")}</span><span>Take control</span></button></div><div id="dialog-overlay" role="dialog" aria-modal="true" aria-labelledby="dialog-message" hidden><div class="browser-dialog"><p id="dialog-message"></p><input id="dialog-prompt" aria-label="Dialog response" hidden><div class="dialog-actions"><button id="dialog-cancel" type="button">Cancel</button><button id="dialog-accept" type="button">OK</button></div></div></div></div><div id="responsive-controls" role="group" aria-label="Responsive viewport controls" hidden><span class="device-select"><select id="device-preset" aria-label="Device preset"><option value="responsive">Responsive</option><option value="iphone-16e">iPhone 16e</option><option value="iphone-17">iPhone 17</option><option value="iphone-17-pro-max">iPhone 17 Pro Max</option><option value="pixel-10">Pixel 10</option><option value="galaxy-s25-ultra">Galaxy S25 Ultra</option><option value="ipad-mini">iPad mini</option><option value="ipad-air-11">iPad Air 11&quot;</option><option value="ipad-pro-13">iPad Pro 13&quot;</option><option value="laptop">Laptop</option><option value="desktop">Desktop</option><option value="custom" hidden>Custom</option></select>${browserIconSvg("ChevronDown")}</span><span class="responsive-divider" aria-hidden="true"></span><span class="responsive-size"><label class="sr-only" for="responsive-width">Width</label><input id="responsive-width" inputmode="numeric" value="412" aria-label="Viewport width"><span aria-hidden="true">×</span><label class="sr-only" for="responsive-height">Height</label><input id="responsive-height" inputmode="numeric" value="915" aria-label="Viewport height"></span><button id="rotate-viewport" title="Rotate viewport" aria-label="Rotate viewport">${browserIconSvg("Rotate")}</button></div><div id="status" data-state="loading" title="Connecting…"><span class="status-dot" aria-hidden="true"></span><span id="resolution"></span><span id="status-message" class="sr-only" role="status">Connecting…</span></div><div id="machine" aria-label="Browser machine">${browserIconSvg("Machine")}<span id="machine-label"></span></div></div><div id="devtools-divider" hidden></div><div id="devtools-wrap" hidden><div id="devtools-header"><span>DevTools</span><button id="devtools-close" type="button" aria-label="Close DevTools">×</button></div><div id="devtools-status" role="status"></div><iframe id="devtools-frame" title="Browser DevTools"></iframe></div></main>
<script>
try{if(parent!==window){const root=parent.document.documentElement;const syncTheme=()=>{const styles=parent.getComputedStyle(root);for(const token of ['background','foreground','sidebar','sidebar-foreground','sidebar-border','muted','muted-foreground','popover','popover-foreground','border','state-hover','state-active','ring','success','warning','destructive','primary','primary-foreground','input']){const value=styles.getPropertyValue('--'+token).trim();if(value&&CSS.supports('color',value))document.documentElement.style.setProperty('--'+token,value);}};syncTheme();const observer=new MutationObserver(syncTheme);observer.observe(root,{attributes:true});addEventListener('pagehide',()=>observer.disconnect(),{once:true});}}catch{}
if(new URL(location.href).searchParams.has('embedded'))document.body.classList.add('embedded');
const id=new URL(location.href).searchParams.get('id');const screen=document.querySelector('#screen'),status=document.querySelector('#status-message'),address=document.querySelector('#url');
let currentUrl='';let paused=false,acting=false,closed=false,vw=1280,vh=800,seq=0,cast=null,lastFrame=0,lastSocketFrame=0,inViewport=true,responsiveEnabled=false,responsiveWidth=412,responsiveHeight=915,responsiveMobile=true,responsivePreset='responsive',responsiveAvailable=false,responsivePending=null,expectedFrameWidth=0,expectedFrameHeight=0,devtoolsPaneOpen=false,devtoolsOpening=false,devtoolsToken='',devtoolsRev='',devtoolsThemeWritten=null,devtoolsWidth=520,devtoolsTokenReady=false,devtoolsAutoOpened=false,viewerInfoReady=false,infoPending=false,dialogState;const clientId=crypto.randomUUID();const queue=[];
async function json(url,options){const r=await fetch(url,{...options,cache:'no-store'});const data=await r.json();if(!r.ok||data.error)throw Error(data.error||r.statusText);return data;}
const statusBadge=document.querySelector('#status');new MutationObserver(()=>{const text=status.textContent||'';statusBadge.title=text;statusBadge.dataset.state=/^(Live|Input completed|URL copied|Session ID copied|You’re controlling)/.test(text)?'ready':/^(Connecting|Working|Resuming)/.test(text)?'loading':'error';}).observe(status,{childList:true,characterData:true,subtree:true});
const viewport=document.querySelector('#viewport'),browserSurface=document.querySelector('#browser-surface');function fit(){const pane=document.querySelector('#page-pane')||viewport,style=getComputedStyle(pane),hasFrame=!!screen.dataset.frame,frameWidth=hasFrame&&!responsivePending?vw:expectedFrameWidth||(responsiveEnabled?responsiveWidth:vw),frameHeight=hasFrame&&!responsivePending?vh:expectedFrameHeight||(responsiveEnabled?responsiveHeight:vh);const w=pane.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight),h=pane.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom);const scale=Math.max(0,Math.min(w/frameWidth,h/frameHeight,1));browserSurface.style.width=frameWidth*scale+'px';browserSurface.style.height=frameHeight*scale+'px';const skeleton=document.querySelector('#viewport-skeleton');skeleton.style.width=frameWidth*scale+'px';skeleton.style.height=frameHeight*scale+'px';}new ResizeObserver(fit).observe(viewport);
${viewerTrace}
const metrics=window.browseMetrics={displayed:0,dropped:0,bytes:0,inputLatencyMs:0,maxInputQueue:0,startedAt:performance.now()};
let statusErrorUntil=0,pendingFrame=null,decodedFrame=null,decoding=false,paintScheduled=false;const paint=screen.getContext('2d',{alpha:false});
function acceptFrame(blob,frame,ack=()=>{}){metrics.bytes+=blob.size;if(pendingFrame){pendingFrame.ack();metrics.dropped++;}pendingFrame={blob,frame,ack};void decodeFrame();}
function drawFrame(){paintScheduled=false;const item=decodedFrame;decodedFrame=null;if(!item)return;const {bitmap,frame}=item;try{if(closed||document.hidden||!inViewport){metrics.dropped++;return;}if((expectedFrameWidth&&(frame.width!==expectedFrameWidth||frame.height!==expectedFrameHeight))||(!expectedFrameWidth&&responsiveEnabled&&(frame.width!==responsiveWidth||frame.height!==responsiveHeight))){metrics.dropped++;return;}if(screen.width!==(bitmap.displayWidth||bitmap.width)||screen.height!==(bitmap.displayHeight||bitmap.height)){screen.width=bitmap.displayWidth||bitmap.width;screen.height=bitmap.displayHeight||bitmap.height;}if(vw!==frame.width||vh!==frame.height){vw=frame.width;vh=frame.height;}const completed=responsivePending;if(completed){responsiveEnabled=completed.enabled;if(completed.enabled){responsiveWidth=completed.width;responsiveHeight=completed.height;responsiveMobile=completed.mobile;responsivePreset=completed.preset;}responsivePending=null;}expectedFrameWidth=0;expectedFrameHeight=0;if(completed)renderResponsive();else fit();const shownWidth=responsiveEnabled?responsiveWidth:vw,shownHeight=responsiveEnabled?responsiveHeight:vh;document.querySelector('#resolution').textContent=shownWidth+' × '+shownHeight;traceSample('paintGap',lastFrame?Date.now()-lastFrame:0);if(item.readyAt)traceSample('paintWait',performance.now()-item.readyAt);paint.drawImage(bitmap,0,0,screen.width,screen.height);screen.dataset.frame='true';document.querySelector('#viewport-skeleton').hidden=true;lastFrame=Date.now();seq=frame.seq||seq;pageLoading=frame.loading===true;document.querySelector('#viewport').dataset.loaded='true';renderCopy();if(completed&&!completed.enabled)setResponsiveTransport(false);if(frame.url){currentUrl=frame.url;if(document.activeElement!==address)address.value=frame.url;}if(!acting&&Date.now()>statusErrorUntil)status.textContent='Live · '+shownWidth+' × '+shownHeight;metrics.displayed++;}finally{bitmap.close();item.ack();}}
async function decodeFrame(){if(decoding||!pendingFrame)return;decoding=true;const item=pendingFrame;pendingFrame=null;let bitmap;try{bitmap=await createImageBitmap(item.blob);if(closed||document.hidden||!inViewport){metrics.dropped++;bitmap.close();item.ack();return;}if(decodedFrame){decodedFrame.bitmap.close();decodedFrame.ack();metrics.dropped++;}decodedFrame={bitmap,frame:item.frame,ack:item.ack,readyAt:performance.now()};if(!paintScheduled){paintScheduled=true;requestAnimationFrame(drawFrame);}}catch(e){bitmap?.close();item.ack();status.textContent='Could not decode browser frame.';}finally{decoding=false;if(pendingFrame)void decodeFrame();}}

function show(frame){if(!frame?.data)return;const bytes=Uint8Array.from(atob(frame.data),c=>c.charCodeAt(0));acceptFrame(new Blob([bytes],{type:'image/jpeg'}),frame);}
new IntersectionObserver(entries=>{inViewport=entries.some(e=>e.isIntersecting&&e.intersectionRatio>0);syncVisibility();void reportPresence();}).observe(viewport);
let lastTelemetry={at:performance.now(),displayed:0,bytes:0};
async function reportPresence(){try{const now=performance.now(),elapsed=Math.max(1,now-lastTelemetry.at);const sample={transport:metrics.transport||"jpeg",host:location.host,fps:(metrics.displayed-lastTelemetry.displayed)*1000/elapsed,mbps:(metrics.bytes-lastTelemetry.bytes)*8/elapsed/1000,inputLatencyMs:Math.min(60000,metrics.inputLatencyMs),displayed:metrics.displayed,dropped:metrics.dropped,streamTier:metrics.streamTier||0,frameAckMs:metrics.frameAckMs||0};lastTelemetry={at:now,displayed:metrics.displayed,bytes:metrics.bytes};const reply=await json('./presence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,clientId,visible:inViewport&&!closed&&!paused&&!document.hidden,metrics:sample,trace:traceReport()})});traceUntil=performance.now()+(reply.traceRemainingMs||0);}catch{}}
const dialogOverlay=document.querySelector('#dialog-overlay'),dialogMessage=document.querySelector('#dialog-message'),dialogPrompt=document.querySelector('#dialog-prompt'),dialogCancel=document.querySelector('#dialog-cancel'),dialogAccept=document.querySelector('#dialog-accept');
function renderDialog(dialog){if(dialog&&dialogState&&!dialogOverlay.hidden&&dialog.type===dialogState.type&&dialog.message===dialogState.message&&dialog.defaultPrompt===dialogState.defaultPrompt)return;dialogState=dialog;if(!dialog){dialogOverlay.hidden=true;dialogPrompt.hidden=true;return;}dialogMessage.textContent=dialog.message||'';dialogPrompt.hidden=dialog.type!=='prompt';dialogCancel.hidden=dialog.type==='alert';if(dialog.type==='prompt'){dialogPrompt.value=dialog.defaultPrompt||'';}dialogOverlay.hidden=false;(dialog.type==='prompt'?dialogPrompt:dialogAccept).focus();}
function respondDialog(accept){if(!dialogState)return;const promptText=dialogState.type==='prompt'?dialogPrompt.value:undefined;withToolbarControl(()=>input({kind:'dialog',accept,promptText},()=>renderDialog(),()=>{}));}
dialogCancel.onclick=()=>respondDialog(false);dialogAccept.onclick=()=>respondDialog(true);dialogPrompt.onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();respondDialog(true);}else if(event.key==='Escape'){event.preventDefault();respondDialog(false);}};
async function refreshViewerInfo(){if(closed||infoPending||document.hidden||!inViewport)return;infoPending=true;try{const info=await json('./viewer-info?id='+encodeURIComponent(id));document.querySelector('#machine-label').textContent=info.hostLabel;responsiveAvailable=info.mode==='managed';if(!viewerInfoReady){viewerInfoReady=true;renderResponsive();if(info.viewport&&(info.viewport.width!==1280||info.viewport.height!==800||info.viewport.mobile))syncResponsive(info.viewport);}if(info.url&&!currentUrl){currentUrl=info.url;if(document.activeElement!==address)address.value=info.url;}renderDialog(info.dialog);if(info.devtoolsOpen&&!devtoolsPaneOpen&&!devtoolsAutoOpened){devtoolsAutoOpened=true;requestDevtoolsPane();}if(['error','released'].includes(info.status)&&!acting){statusErrorUntil=Date.now()+1500;status.textContent=info.error||'Browser closed';}}catch(e){if(!viewerInfoReady){responsiveAvailable=false;renderResponsive();status.textContent=e.message;}}finally{infoPending=false;}}
void refreshViewerInfo();const viewerInfoTimer=setInterval(refreshViewerInfo,1000);
setInterval(()=>{if(inViewport&&!document.hidden)void reportPresence();},4000);document.addEventListener('visibilitychange',reportPresence);
function point(e){const r=screen.getBoundingClientRect();return{x:Math.min(vw-1,Math.max(0,(e.clientX-r.left)*vw/r.width)),y:Math.min(vh-1,Math.max(0,(e.clientY-r.top)*vh/r.height))};}
${videoClient}
function openCast(){if(closed||paused||document.hidden||!inViewport||cast)return;if(videoMode){openVideo();return;}const ws=new WebSocket((location.protocol==='https:'?'wss:':'ws:')+'//'+location.host+location.pathname.replace(/\\/viewer$/,'/cast')+'?id='+encodeURIComponent(id)+'&binary=1');cast=ws;let metadata;ws.onmessage=e=>{try{if(typeof e.data==='string'){const f=JSON.parse(e.data);if(f.error){status.textContent=f.error;ws.close();}else metadata=f;}else if(metadata){const frame=metadata,receivedAt=performance.now();metadata=null;lastSocketFrame=Date.now();metrics.streamTier=frame.streamTier||0;metrics.frameAckMs=frame.ackMs||0;acceptFrame(e.data,frame,()=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({ack:frame.seq,clientMs:Math.round(performance.now()-receivedAt)}));});}}catch{}};ws.onclose=()=>{if(cast===ws)cast=null;if(!closed&&!paused&&!document.hidden&&inViewport)setTimeout(openCast,400);};ws.onerror=()=>ws.close();}
async function poll(){if(closed)return;try{if(!videoMode&&!paused&&!document.hidden&&inViewport&&(!cast||cast.readyState!==WebSocket.OPEN))show(await json('./frame?id='+encodeURIComponent(id)+'&after='+seq));}catch(e){status.textContent=e.message;}finally{if(!closed)setTimeout(poll,1000);}}
function input(action,onComplete,onError){if(queue.length>=100){const error=Error('Input queue is full; wait for pending input.');onError?.(error);status.textContent=error.message;return;}queue.push({action,onComplete,onError});if(!acting)void drain();}
async function drain(){if(!queue.length||closed)return;if(!hasControl){const error=Error('Take control before interacting.');for(const pending of queue.splice(0))pending.onError?.(error);status.textContent=error.message;return;}acting=true;const pending=queue.shift(),action=pending.action;navigationPending=action.kind==='navigate'||action.kind==='history'||(action.kind==='maintenance'&&action.action==='hard-reload');renderCopy();status.textContent='Working…';try{let job=await json('./input',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,clientId,input:action})});while(job.status==='running'){await new Promise(r=>setTimeout(r,100));job=await json('./viewer-job?id='+encodeURIComponent(id)+'&job='+encodeURIComponent(job.id));}if(job.status!=='succeeded')throw Error(job.error||job.status);pending.onComplete?.();status.textContent='Input completed';}catch(e){pending.onError?.(e);for(const queued of queue.splice(0))queued.onError?.(e);status.textContent=e.message;}finally{acting=false;navigationPending=false;renderCopy();if(queue.length)void drain();}}
for(const action of ['back','forward','reload'])document.querySelector('#'+action).onclick=()=>input({kind:'history',action});
function navigateAddress(){try{const text=address.value.trim();const url=new URL(text.includes('://')?text:'https://'+text);if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw Error('Enter an HTTP or HTTPS address without login details.');input({kind:'navigate',url:url.href});}catch(e){status.textContent=e.message;}}address.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();navigateAddress();}};
document.querySelector('#open-external').onclick=()=>{try{Promise.resolve((${openClientExternal.toString()})(currentUrl,window)).catch(e=>{status.textContent='Could not open externally: '+e.message;});}catch(e){status.textContent='Could not open externally: '+e.message;}};
const copyUrlButton=document.querySelector('#copy-url');let copyReset,pageLoading=true,navigationPending=false,copied=false;
function renderCopy(){const state=pageLoading||navigationPending?'loading':copied?'copied':'idle';if(copyUrlButton.dataset.state===state)return;copyUrlButton.dataset.state=state;copyUrlButton.disabled=state==='loading';copyUrlButton.innerHTML=state==='loading'?${JSON.stringify(browserIconSvg("Loading"))}:state==='copied'?${JSON.stringify(browserIconSvg("Check"))}:${JSON.stringify(browserIconSvg("Copy"))};const label=state==='loading'?'Loading':state==='copied'?'Copied':'Copy current URL';copyUrlButton.dataset.tooltip=label;copyUrlButton.setAttribute('aria-label',label);}
function resetCopy(){clearTimeout(copyReset);copied=false;renderCopy();}
copyUrlButton.onclick=async()=>{try{if(!currentUrl)throw Error('No page URL to copy yet.');await navigator.clipboard.writeText(currentUrl);clearTimeout(copyReset);copied=true;renderCopy();copyReset=setTimeout(resetCopy,1500);status.textContent='URL copied';}catch(e){resetCopy();status.textContent='Could not copy URL: '+e.message;}};
renderCopy();addEventListener('pagehide',()=>clearTimeout(copyReset),{once:true});
document.querySelector('#copy-session').onclick=async()=>{try{await navigator.clipboard.writeText(id);status.textContent='Session ID copied';}catch(e){status.textContent='Could not copy session ID: '+e.message;}};
const tooltip=document.createElement('div');tooltip.id='action-tooltip';tooltip.role='tooltip';tooltip.hidden=true;document.body.append(tooltip);let tooltipTimer,tooltipTarget;
function hideTooltip(){clearTimeout(tooltipTimer);tooltip.hidden=true;tooltipTarget?.removeAttribute('aria-describedby');tooltipTarget=null;}
function showTooltip(target){hideTooltip();tooltipTimer=setTimeout(()=>{tooltipTarget=target;tooltip.textContent=target.dataset.tooltip;tooltip.hidden=false;const r=target.getBoundingClientRect(),t=tooltip.getBoundingClientRect();tooltip.style.left=Math.max(8,Math.min(innerWidth-t.width-8,r.left+(r.width-t.width)/2))+'px';tooltip.style.top=(r.bottom+t.height+8<innerHeight?r.bottom+4:Math.max(4,r.top-t.height-4))+'px';target.setAttribute('aria-describedby',tooltip.id);},400);}
for(const action of document.querySelectorAll('header button,header summary,#responsive-controls button')){action.dataset.tooltip=action.dataset.tooltip||action.title||action.getAttribute('aria-label')||action.textContent.trim();action.removeAttribute('title');action.addEventListener('pointerenter',()=>showTooltip(action));action.addEventListener('pointerleave',hideTooltip);action.addEventListener('focus',()=>{if(action.matches(':focus-visible'))showTooltip(action);});action.addEventListener('blur',hideTooltip);action.addEventListener('click',hideTooltip);}
document.addEventListener('keydown',event=>{if(event.key==='Escape')hideTooltip();});addEventListener('pagehide',hideTooltip,{once:true});
const options=document.querySelector('details'),summary=options.querySelector('summary'),menu=options.querySelector('.menu');
function devtoolsWantTheme(){const theme=new URL(location.href).searchParams.get('bbTheme');return theme==='light'?'light':'dark';}
function seedDevtoolsTheme(mode){const want=mode==='light'?'"default"':'"dark"';let current=null;try{current=localStorage.getItem('ui-theme');}catch{return false;} if(current===want){devtoolsThemeWritten=want;return false;} if(current!==null&&devtoolsThemeWritten===want){return false;} try{localStorage.setItem('ui-theme',want);}catch{return false;} devtoolsThemeWritten=want;return true;}
function renderDevtools(){const wrap=document.querySelector('#devtools-wrap'),divider=document.querySelector('#devtools-divider');viewport.dataset.devtools=String(devtoolsPaneOpen);if(wrap){wrap.hidden=!devtoolsPaneOpen;if(devtoolsPaneOpen)wrap.style.width=devtoolsWidth+'px';}if(divider)divider.hidden=!devtoolsPaneOpen;fit();}
function devtoolsFrameUrl(token,rev){const target=location.host+'/api/v1/plugins/browse/http/devtools-ws?token='+token;return './devtools/'+encodeURIComponent(rev)+'/'+encodeURIComponent(token)+'/inspector.html?ws='+encodeURIComponent(target);}
async function ensureDevtoolsSW(){if(!('serviceWorker' in navigator))throw Error('Service workers are unavailable in this browser.');const registration=await navigator.serviceWorker.register('./devtools-sw.js',{scope:'./devtools/'});await registration.update().catch(()=>{});const worker=registration.installing||registration.waiting||registration.active;if(worker&&worker.state!=='activated')await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('DevTools service timed out.')),10000);worker.addEventListener('statechange',()=>{if(worker.state==='activated'){clearTimeout(timer);resolve();}});});}
async function openDevtoolsPane(){
  if((devtoolsPaneOpen&&devtoolsTokenReady)||devtoolsOpening)return;
  devtoolsOpening=true;devtoolsPaneOpen=true;devtoolsTokenReady=false;renderDevtools();
  const note=document.querySelector('#devtools-status');if(note)note.textContent='Connecting…';
  try{
    if(!responsiveAvailable)throw Error('DevTools needs a managed Browse session.');
    const grant=await json('./devtools-token?id='+encodeURIComponent(id)+'&clientId='+encodeURIComponent(clientId));
    devtoolsToken=grant.token;devtoolsRev=grant.rev;
    await ensureDevtoolsSW();
    seedDevtoolsTheme(devtoolsWantTheme());
    document.querySelector('#devtools-frame').src=devtoolsFrameUrl(devtoolsToken,devtoolsRev);
    devtoolsTokenReady=true;
    if(note)note.textContent='';
  }catch(e){status.textContent=e instanceof Error?e.message:String(e);closeDevtoolsPane();}
  finally{devtoolsOpening=false;}
}
function closeDevtoolsPane(){devtoolsOpening=false;devtoolsPaneOpen=false;devtoolsTokenReady=false;devtoolsToken='';const frame=document.querySelector('#devtools-frame');if(frame)frame.src='about:blank';const note=document.querySelector('#devtools-status');if(note)note.textContent='';renderDevtools();}
function requestDevtoolsPane(){if((devtoolsPaneOpen&&devtoolsTokenReady)||devtoolsOpening)return;if(typeof hasControl!=='undefined'&&!hasControl)status.textContent='Taking control…';withToolbarControl(()=>{void openDevtoolsPane();});}
function toggleDevtoolsPane(){if(devtoolsPaneOpen){closeDevtoolsPane();return;}withToolbarControl(()=>{input({kind:'maintenance',action:'open-devtools'},undefined,()=>{});});requestDevtoolsPane();}
document.querySelector('#devtools-close').onclick=()=>closeDevtoolsPane();
const devtoolsDivider=document.querySelector('#devtools-divider');
devtoolsDivider.addEventListener('pointerdown',event=>{if(!devtoolsPaneOpen||!event.isPrimary)return;event.preventDefault();try{devtoolsDivider.setPointerCapture(event.pointerId);}catch{} const pointerId=event.pointerId;const move=ev=>{if(ev.pointerId!==pointerId)return;const bounds=viewport.getBoundingClientRect();devtoolsWidth=Math.round(Math.max(320,Math.min(bounds.width-360,bounds.right-ev.clientX-8)));renderDevtools();};const done=ev=>{if(ev.pointerId!==pointerId)return;devtoolsDivider.removeEventListener('pointermove',move);devtoolsDivider.removeEventListener('pointerup',done);devtoolsDivider.removeEventListener('pointercancel',done);};devtoolsDivider.addEventListener('pointermove',move);devtoolsDivider.addEventListener('pointerup',done);devtoolsDivider.addEventListener('pointercancel',done);});
addEventListener('message',event=>{if(event.origin!==location.origin)return;const data=event.data;if(!data||data.type!=='browse-devtools-theme'||(data.mode!=='dark'&&data.mode!=='light'))return;if(seedDevtoolsTheme(data.mode)&&devtoolsPaneOpen){const frame=document.querySelector('#devtools-frame');if(frame&&frame.src&&frame.src.indexOf('about:')!==0)frame.src=frame.src;}});
for(const button of document.querySelectorAll('[data-maintenance]'))button.onclick=()=>{options.open=false;summary.focus();if(button.dataset.maintenance==='open-devtools')toggleDevtoolsPane();else withToolbarControl(()=>{input({kind:'maintenance',action:button.dataset.maintenance});});};
document.addEventListener('pointerdown',event=>{if(!options.contains(event.target))options.open=false;});
options.addEventListener('keydown',event=>{const items=[...menu.querySelectorAll('[role=menuitem]')];if(event.key==='Escape'){event.preventDefault();options.open=false;summary.focus();}else if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)){event.preventDefault();options.open=true;const index=items.indexOf(document.activeElement);items[event.key==='Home'?0:event.key==='End'?items.length-1:(index+(event.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus();}});
const responsiveToggle=document.querySelector('#responsive-toggle'),responsiveControls=document.querySelector('#responsive-controls'),devicePreset=document.querySelector('#device-preset'),responsiveWidthInput=document.querySelector('#responsive-width'),responsiveHeightInput=document.querySelector('#responsive-height');
const devicePresets={responsive:[412,915,true],"iphone-16e":[390,844,true],"iphone-17":[402,874,true],"iphone-17-pro-max":[440,956,true],"pixel-10":[412,923,true],"galaxy-s25-ultra":[384,832,true],"ipad-mini":[744,1133,true],"ipad-air-11":[820,1180,true],"ipad-pro-13":[1032,1376,true],laptop:[1366,768,false],desktop:[1920,1080,false]};
const responsiveLoadingIcon=${JSON.stringify(browserIconSvg("Loading"))},responsivePhoneIcon=${JSON.stringify(browserIconSvg("Responsive"))};
function renderResponsive(){const shownEnabled=responsivePending?responsivePending.enabled:responsiveEnabled;const shownWidth=responsivePending?responsivePending.width:(responsiveEnabled?responsiveWidth:vw);const shownHeight=responsivePending?responsivePending.height:(responsiveEnabled?responsiveHeight:vh);const shownPreset=responsivePending?responsivePending.preset:responsivePreset;const responsiveStaging=!!responsivePending;responsiveToggle.setAttribute('aria-pressed',String(shownEnabled));responsiveToggle.disabled=!responsiveAvailable||responsiveStaging;if((responsiveToggle.dataset.busy??'')!==String(responsiveStaging)){responsiveToggle.dataset.busy=String(responsiveStaging);responsiveToggle.innerHTML=responsiveStaging?responsiveLoadingIcon:responsivePhoneIcon;}if(responsiveStaging){responsiveToggle.setAttribute('data-pending','true');}else{responsiveToggle.removeAttribute('data-pending');}responsiveToggle.setAttribute('aria-label',responsiveStaging?'Switching viewport…':'Responsive mode');responsiveToggle.dataset.tooltip=responsiveToggle.getAttribute('aria-label');responsiveControls.hidden=!shownEnabled;viewport.dataset.responsive=String(shownEnabled);devicePreset.value=shownPreset;responsiveWidthInput.value=String(shownWidth);responsiveHeightInput.value=String(shownHeight);for(const item of [devicePreset,responsiveWidthInput,responsiveHeightInput,document.querySelector('#rotate-viewport')])item.disabled=!responsiveAvailable||!!responsivePending||(typeof takingControl!=='undefined'&&takingControl);document.querySelector('#resolution').textContent=shownWidth+' × '+shownHeight;fit();}
function responsiveNeedsControl(){return typeof hasControl!=='undefined'&&!hasControl;}
function noteResponsiveQueued(){if(responsivePending){status.textContent='Working…';}else if(responsiveNeedsControl()){status.textContent='Taking control…';}}
let responsiveCommitSent=false;
function onControlQueueCleared(){if(!responsiveCommitSent&&responsivePending){cancelResponsive();}if(devtoolsPaneOpen&&!devtoolsTokenReady){closeDevtoolsPane();status.textContent='DevTools control released.';}}
function syncResponsive(value){responsiveCommitSent=true;stageResponsive(true,value.width,value.height,value.mobile,'custom');setResponsiveTransport(true);}
function prepareViewportFrame(width=responsiveWidth,height=responsiveHeight){expectedFrameWidth=width;expectedFrameHeight=height;if(!screen.dataset.frame){viewport.dataset.loaded='false';document.querySelector('#viewport-skeleton').hidden=false;}fit();}
function stageResponsive(enabled,width,height,mobile,preset){if(responsivePending)return false;responsivePending={enabled,width,height,mobile,preset};prepareViewportFrame(width,height);if(enabled)setResponsiveTransport(true);renderResponsive();return true;}
function cancelResponsive(){responsivePending=null;expectedFrameWidth=0;expectedFrameHeight=0;setResponsiveTransport(responsiveEnabled);renderResponsive();}
function requestResponsive(enabled,width,height,mobile,preset){if(!responsiveAvailable){status.textContent='Connecting…';return false;}const same=(value)=>value.enabled===enabled&&value.width===width&&value.height===height&&value.mobile===mobile;if(responsivePending)return same(responsivePending);if(same({enabled:responsiveEnabled,width:responsiveWidth,height:responsiveHeight,mobile:responsiveMobile})){responsivePreset=preset;renderResponsive();return true;}responsiveCommitSent=false;if(!stageResponsive(enabled,width,height,mobile,preset))return false;withToolbarControl(()=>{responsiveCommitSent=true;input({kind:'viewport',width,height,mobile},undefined,()=>{responsiveCommitSent=false;cancelResponsive();});});return true;}
responsiveToggle.onclick=()=>{if(!responsiveAvailable){status.textContent='Connecting…';return;}noteResponsiveQueued();requestResponsive(!responsiveEnabled,responsiveEnabled?1280:responsiveWidth,responsiveEnabled?800:responsiveHeight,responsiveEnabled?false:responsiveMobile,responsiveEnabled?'responsive':responsivePreset);};
devicePreset.onchange=()=>{const key=devicePreset.value,preset=devicePresets[key];if(!preset)return;if(!responsiveAvailable){status.textContent='Connecting…';renderResponsive();return;}noteResponsiveQueued();requestResponsive(true,preset[0],preset[1],preset[2],key);};
function applyCustomSize(){const width=Math.max(320,Math.min(2560,Number.parseInt(responsiveWidthInput.value,10)||responsiveWidth)),height=Math.max(320,Math.min(2560,Number.parseInt(responsiveHeightInput.value,10)||responsiveHeight));if(!responsiveAvailable){status.textContent='Connecting…';renderResponsive();return;}noteResponsiveQueued();requestResponsive(true,width,height,width<1024,'custom');}
responsiveWidthInput.onchange=applyCustomSize;responsiveHeightInput.onchange=applyCustomSize;
document.querySelector('#rotate-viewport').onclick=()=>{if(!responsiveAvailable){status.textContent='Connecting…';return;}noteResponsiveQueued();requestResponsive(true,responsiveHeight,responsiveWidth,responsiveMobile,'custom');};
${viewerInteraction}
window.addEventListener('pagehide' ,()=>{closed=true;clearInterval(viewerInfoTimer);stopVideo();if(decodedFrame){decodedFrame.bitmap.close();decodedFrame=null;}cast&&cast.close();void reportPresence();});openCast();poll();
</script></body></html>`;
