// Runs only inside the authenticated viewer; no agent job is created for human input.
export const viewerInteraction = String.raw`
let control=null,hasControl=false,takingControl=false,controlIntent='explicit',controlSeq=0,inflight=new Map(),sendScheduled=false,selectedText='',heldPointer=null,clickAt=0,clickPoint=null,clickCount=0;const pendingControlActions=[];
const directQueue=[];const keyboard=document.createElement('textarea');keyboard.id='browser-keyboard';keyboard.setAttribute('aria-label','Browser keyboard input');keyboard.autocomplete='off';keyboard.autocapitalize='off';keyboard.spellcheck=false;document.body.append(keyboard);
const controlToggle=document.querySelector('#control-toggle'),controlLabel=controlToggle.querySelector(':scope > span:last-child'),controlCursor=controlToggle.querySelector('[data-kind="cursor"]'),controlLoading=controlToggle.querySelector('[data-kind="loading"]');
function renderControl(){const explicitTaking=takingControl&&controlIntent==='explicit';viewport.dataset.control=explicitTaking?'taking':hasControl?'human':'agent';controlLabel.textContent='Take control';controlCursor.hidden=explicitTaking;controlLoading.hidden=!explicitTaking;controlToggle.disabled=explicitTaking;if(typeof renderResponsive!=='undefined')renderResponsive();address.readOnly=!hasControl;for(const key of ['back','forward','reload'])document.querySelector('#'+key).disabled=!hasControl;screen.setAttribute('aria-label',hasControl?'Live browser; select text, click, drag, type, paste and scroll':'Live browser view; take control to interact');}
const mods=e=>((e.getModifierState?.('AltGraph')?0:(e.altKey?1:0)|(e.ctrlKey?2:0))|(e.metaKey?4:0)|(e.shiftKey?8:0));
function controlUrl(){return(location.protocol==='https:'?'wss:':'ws:')+'//'+location.host+location.pathname.replace(/\/viewer$/,'/control')+'?id='+encodeURIComponent(id)+'&clientId='+encodeURIComponent(clientId);}
function withHumanControl(action,{silent=false}={}){if(hasControl){action();return;}pendingControlActions.push(action);openControl({silent});}
function withToolbarControl(action){withHumanControl(action,{silent:true});}
function openControl({silent=false}={}){if(closed||document.hidden||!inViewport||hasControl)return;if(control||takingControl){if(!silent&&takingControl&&controlIntent!=='explicit'){controlIntent='explicit';renderControl();}return;}controlIntent=silent?'silent':'explicit';takingControl=true;renderControl();const ws=new WebSocket(controlUrl());control=ws;
 ws.onopen=()=>ws.send(JSON.stringify({type:'take'}));
 ws.onmessage=e=>{let result;try{result=JSON.parse(e.data);}catch{return;}if(result.type==='control'){const explicit=controlIntent==='explicit';takingControl=false;if(result.state==='human'){hasControl=true;status.textContent=explicit?'You’re controlling':'Working…';renderControl();if(explicit)keyboard.focus({preventScroll:true});flushDirect();const actions=pendingControlActions.splice(0);controlIntent='explicit';for(const action of actions)action();}else{pendingControlActions.length=0;if(typeof onControlQueueCleared!=='undefined')onControlQueueCleared();controlIntent='explicit';status.textContent=result.state==='busy'?'Another viewer has control.':result.error||'Could not take control.';renderControl();if(result.state!=='human')ws.close();}return;}const sent=inflight.get(result.seq);if(!sent)return;metrics.inputLatencyMs=performance.now()-sent.at;traceSample('inputRtt',metrics.inputLatencyMs);traceSample('hostInput',result.hostMs);clearTimeout(sent.timer);inflight.delete(result.seq);if(result.error){directQueue.length=0;selectedText='';status.textContent=result.error;statusErrorUntil=Date.now()+3000;}else{if(typeof result.selection==='string')selectedText=result.selection;if(typeof result.cursor==='string'&&/^[a-z-]+$/.test(result.cursor))screen.style.cursor=result.cursor;}flushDirect();};
 ws.onclose=()=>{if(control!==ws)return;control=null;hasControl=false;takingControl=false;controlIntent='explicit';pendingControlActions.length=0;if(typeof onControlQueueCleared!=='undefined')onControlQueueCleared();directQueue.length=0;for(const sent of inflight.values())clearTimeout(sent.timer);inflight.clear();heldPointer=null;keysDown.clear();status.textContent='Live';renderControl();};ws.onerror=()=>ws.close();}
function flushDirect(){sendScheduled=false;if(inflight.size>=3||!directQueue.length||control?.readyState!==WebSocket.OPEN)return;const seq=++controlSeq;const events=[];let size=32;while(directQueue.length&&events.length<64){const next=directQueue[0],bytes=JSON.stringify(next).length+1;if(events.length&&size+bytes>60000)break;traceSample('inputQueue',performance.now()-(next.queuedAt||performance.now()));events.push(directQueue.shift());size+=bytes;}const ws=control;inflight.set(seq,{at:performance.now(),timer:setTimeout(()=>{status.textContent='Browser input connection timed out.';ws.close();},10000)});ws.send(JSON.stringify({seq,events}));}
function direct(event){if(document.hidden||!inViewport||closed||!hasControl)return;if(control?.readyState!==WebSocket.OPEN){status.textContent='Browser input disconnected.';return;}Object.defineProperty(event,'queuedAt',{value:performance.now(),enumerable:false});const last=directQueue.at(-1);
 if(event.kind==='pointer'&&event.type==='move'&&last?.kind==='pointer'&&last.type==='move')directQueue[directQueue.length-1]=event;
 else if(event.kind==='wheel'&&last?.kind==='wheel'&&event.modifiers===last.modifiers){last.deltaX=Math.max(-3000,Math.min(3000,last.deltaX+event.deltaX));last.deltaY=Math.max(-3000,Math.min(3000,last.deltaY+event.deltaY));last.x=event.x;last.y=event.y;}
 else if(directQueue.length<256)directQueue.push(event);else{status.textContent='Browser input queue is full.';control.close();return;}
 metrics.maxInputQueue=Math.max(metrics.maxInputQueue,directQueue.length);if(!sendScheduled){sendScheduled=true;requestAnimationFrame(flushDirect);}}
function releaseInput(){if(control?.readyState===WebSocket.OPEN){directQueue.length=0;directQueue.push({kind:'reset'});flushDirect();}heldPointer=null;keysDown.clear();}
const buttonName=e=>e.button===2?'right':e.button===1?'middle':e.button===0?'left':'none';
screen.addEventListener('pointerdown',e=>{if(!e.isPrimary)return;e.preventDefault();keyboard.focus({preventScroll:true});screen.setPointerCapture(e.pointerId);const p=point(e);const now=performance.now();clickCount=clickPoint&&Math.hypot(p.x-clickPoint.x,p.y-clickPoint.y)<5&&now-clickAt<400?Math.min(3,clickCount+1):1;clickAt=now;clickPoint=p;heldPointer={id:e.pointerId,button:buttonName(e),...p,buttons:e.buttons,modifiers:mods(e)};selectedText='';direct({kind:'pointer',type:'down',...p,button:buttonName(e),buttons:e.buttons,clickCount,modifiers:mods(e)});});
screen.addEventListener('pointermove',e=>{if(!e.isPrimary)return;const p=point(e);if(heldPointer)Object.assign(heldPointer,p,{buttons:e.buttons,modifiers:mods(e)});direct({kind:'pointer',type:'move',...p,button:heldPointer?.button||'none',buttons:e.buttons,clickCount:0,modifiers:mods(e)});});
screen.addEventListener('pointerup',e=>{if(!e.isPrimary)return;e.preventDefault();direct({kind:'pointer',type:'up',...point(e),button:buttonName(e),buttons:e.buttons,clickCount,modifiers:mods(e)});if(e.buttons&&heldPointer){heldPointer.buttons=e.buttons;return;}heldPointer=null;if(screen.hasPointerCapture(e.pointerId))screen.releasePointerCapture(e.pointerId);});
screen.addEventListener('pointercancel',releaseInput);screen.addEventListener('lostpointercapture',()=>{if(heldPointer)releaseInput();});
screen.addEventListener('contextmenu',e=>e.preventDefault());screen.addEventListener('dragstart',e=>e.preventDefault());
screen.addEventListener('wheel',e=>{e.preventDefault();const unit=e.deltaMode===1?16:e.deltaMode===2?vh:1;direct({kind:'wheel',...point(e),deltaX:Math.max(-3000,Math.min(3000,e.deltaX*unit)),deltaY:Math.max(-3000,Math.min(3000,e.deltaY*unit)),modifiers:mods(e)});},{passive:false});
const keysDown=new Set();let composing=false,compositionCommit=null;
keyboard.addEventListener('keydown',e=>{if(e.isComposing||composing||['Dead','Process','Unidentified'].includes(e.key))return;const shortcut=!!(mods(e)&6);if(shortcut&&['c','x','v'].includes(e.key.toLowerCase()))return;e.preventDefault();keysDown.add(e.code);direct({kind:'keyboard',type:'down',key:e.key,code:e.code,modifiers:mods(e),repeat:e.repeat});});
keyboard.addEventListener('keyup',e=>{if(!keysDown.delete(e.code))return;e.preventDefault();direct({kind:'keyboard',type:'up',key:e.key,code:e.code,modifiers:mods(e),repeat:false});});
keyboard.addEventListener('compositionstart',()=>{composing=true;compositionCommit=null;});keyboard.addEventListener('compositionend',e=>{composing=false;compositionCommit=e.data;setTimeout(()=>compositionCommit=null,0);if(e.data)direct({kind:'text',text:e.data.slice(0,10000)});keyboard.value='';});
keyboard.addEventListener('beforeinput',e=>{if(composing||e.isComposing)return;if(['insertText','insertFromComposition'].includes(e.inputType)&&e.data){e.preventDefault();if(e.data===compositionCommit){compositionCommit=null;return;}direct({kind:'text',text:e.data.slice(0,10000)});}});
keyboard.addEventListener('input',()=>{if(!composing)keyboard.value='';});
keyboard.addEventListener('paste',e=>{e.preventDefault();const text=e.clipboardData.getData('text/plain');if(text)direct({kind:'text',text:text.slice(0,10000)});});
for(const event of ['copy','cut'])keyboard.addEventListener(event,e=>{e.preventDefault();if(!selectedText)return;e.clipboardData.setData('text/plain',selectedText);if(event==='cut'){direct({kind:'keyboard',type:'down',key:'Backspace',code:'Backspace',modifiers:0,repeat:false});direct({kind:'keyboard',type:'up',key:'Backspace',code:'Backspace',modifiers:0,repeat:false});selectedText='';}});
screen.addEventListener('focus',()=>keyboard.focus({preventScroll:true}));keyboard.addEventListener('blur',releaseInput);window.addEventListener('blur',releaseInput);
const heldHeartbeat=setInterval(()=>{if(!heldPointer&&keysDown.size)direct({kind:'heartbeat'});if(heldPointer)direct({kind:'pointer',type:'move',x:heldPointer.x,y:heldPointer.y,button:heldPointer.button,buttons:heldPointer.buttons,clickCount:0,modifiers:heldPointer.modifiers});},2000);
function syncVisibility(){if(document.hidden||!inViewport){releaseInput();control?.close();cast?.close();if(pendingFrame){pendingFrame.ack();pendingFrame=null;metrics.dropped++;}if(decodedFrame){decodedFrame.bitmap.close();decodedFrame.ack();decodedFrame=null;metrics.dropped++;}}else openCast();}
document.addEventListener('visibilitychange',syncVisibility);
controlToggle.onclick=()=>openControl();renderControl();
addEventListener('pagehide',()=>{clearInterval(heldHeartbeat);control?.close();directQueue.length=0;},{once:true});
`;
