export const meta = {
  name: "wayfinder-build",
  description: "Build Wayfinder's shared-computer browser/desktop testing plugin with Opus 5 and GPT-5.6-Sol, then independently review and fix it.",
  phases: [
    { title: "Foundation", detail: "Contracts, scaffold, and real host capability probes" },
    { title: "Implementation", detail: "Engine/adapters and Computer UI/media in disjoint files" },
    { title: "Integration", detail: "Wire BB lifecycle, tools, artifacts, and UI; verify and deploy safely" },
    { title: "Review", detail: "Independent correctness, safety, and performance review" },
    { title: "Fix and verify", detail: "Regression fixes and evidence-based release report" }
  ]
};
const common = `Work in /home/g4f4r0/projects/bb-plugins, permanent live plugin source. The user authorized implementation, not just a proposal. Read README.md, .bb/AGENTS.md, bb-plugin-wayfinder/PLAN.md and applicable bb-plugin-authoring, bb-cli, git-operation skills/references. Follow current SDK declarations rather than guessing. PLAN.md supersedes the earlier Python/browser-only proposal. Implement simple, reliable, performant TypeScript/Node + Effect with Fortress/Jev browser execution and direct Cua runtime desktop integration, scoped filesystem verification, one shared computer/controller, private Computer sidebar live view, optimized inline images/videos with Copy/Download/Share, and secure online artifact exports. Do not reinstall the removed cua-driver, browse, or browser-automation BB plugins. Native Cua runtime integration is authorized, but privileged/system installs require user consent. No per-thread VM. No mandatory Python sidecar. No nested subagents or workflows. Use Infisical for all secrets; verify project/env/path before access, never expose values or create .env files; missing auth/scope is a prerequisite blocker, never guess. Use synthetic local fixtures and approved safe interactions only; no real consequential transactions. Preserve unrelated changes and never push. Do not pretend mocks establish live success. No browser/cdp/driver ports publicly exposed. Report actual commands/results, exact blockers, and files. Keep final response <= 1500 words. All workers share this checkout: observe file ownership strictly.`;
phase("Foundation");
const foundation = await agent(common + `\nSTEP 1: Own the initial scaffold and shared contracts. Implement this step now, not a roadmap. Inspect existing code, actual installed executable availability, SDK UI/HTTP/host/lifecycle contracts, and the pinned upstream references in PLAN. Probe Fortress/CDP and native prerequisites safely without secrets or interactive private apps. Scaffold the actual package with pinned dependencies/lockfile and test/typecheck/build commands. Define stable strictly validated route/run/adapter/media/artifact contracts and interfaces before fanout. Prepare directories/tests with explicit ownership: engine agent owns worker/, src/core/, src/adapters/, src/policy/, src/fs/ and matching tests; UI/media agent owns app.tsx, components/, src/media/, src/artifacts/, frontend styles and matching tests. You own shared contract files, package/lockfiles, server.ts/host.ts initial stubs and IMPLEMENTATION.md in this phase. Install shared needed dependencies now or record integration needs. Shared stubs must be labeled and not deployed. Leave production engine/UI work to following agents. Record findings in IMPLEMENTATION.md and commit only foundation changes if checks pass, no install/deploy yet. Return exact contract/interface paths, APIs, commands, native/provider prerequisites, and ownership boundaries so both downstream agents can implement independently.`, { provider: "codex", model: "gpt-5.6-sol", reasoningLevel: "high", label: "Foundation and contracts", phase: "Foundation" });
if (!foundation) throw new Error("Foundation produced no result; refusing blind fanout");
phase("Implementation");
const implementations = await parallel([
  () => agent(common + `\nSTEP 2: Implement the execution engine and browser/native/filesystem adapters now against the published contracts. You own ONLY worker/, src/core/, src/adapters/, src/policy/, src/fs/, and clearly named engine tests under bb-plugin-wayfinder. Do not edit package.json/lockfile, shared contracts, server.ts/host.ts/app.tsx, docs, media/artifact modules, or UI files during this parallel phase. If additional dependencies or contract changes are necessary, document them in your final response for integration rather than racing edits. Implement real provider/CDP/Cua integration with readiness reporting, host-wide single-controller queue/lease, stale-target guards, independent verification, bounded decisions and output, cancellation and crash/uncertain-mutation recovery, scoped filesystem checks, synthetic fixtures and tests. Use Effect where it materially simplifies lifecycle without abstractions for their own sake. Model confidence never overrides policy; do not implement arbitrary model scripts or unrestricted shell. Don't treat a missing provider key or native runtime as success; implement functional capability probes and setup-required results. Run owned tests and typecheck as applicable. Do not stage/commit or deploy in the parallel phase. Return concrete interfaces, tests, setup blockers, and integration tasks.\nFOUNDATION RESULT:\n` + foundation, { provider: "codex", model: "gpt-5.6-sol", reasoningLevel: "high", label: "Execution engine and adapters", phase: "Implementation" }),
  () => agent(common + `\nSTEP 3: Implement the Computer UI and media/artifact components now against the published contracts. Own ONLY app.tsx, components/, src/media/, src/artifacts/, frontend styles and clearly named media/UI/artifact tests under bb-plugin-wayfinder. Do not edit package.json/lockfile, shared contracts, server.ts/host.ts, engine/policy/fs directories, or docs during this parallel phase. Report dependency/contract needs in your final response for integration. Use actual supported BB SDK slots for Computer sidebar and inline thread artifact cards; do not invent SDK APIs or patch BB's private DOM. Implement read-only live view with queue/owner/connection/frame-age states, bounded capture/streaming and optimized media services, Copy/Download/Share controls with clear fallbacks, safe range-streamed video and authenticated scoped artifact/export services. External sharing stays disabled if signing prerequisites are absent; no homemade persisted secrets. Add tests for cross-thread access, unsafe paths/HTML, expiry/revocation, slow viewers and clipboard fallback. No placeholder button may be advertised as working. Run owned tests. Do not stage/commit/deploy in the parallel phase. Return exact wiring needs and blockers.\nFOUNDATION RESULT:\n` + foundation, { provider: "claude-code", model: "claude-opus-5", reasoningLevel: "high", label: "Computer UI, media, and artifacts", phase: "Implementation" })
]);
if (implementations.some(x => x === null)) throw new Error("Implementation worker failed; inspect partial work before integration");
phase("Integration");
const integration = await agent(common + `\nSTEP 4: Integrate both completed implementation branches, owning all Wayfinder files serially now. Read their code rather than relying on reports. Resolve dependencies/contracts and implement real server.ts/host.ts lifecycle, tools/CLI, settings, RPC/HTTP, artifact/UI bindings, host control locking, and secret-safe provider startup. Read installed SDK declarations and test build rather than fabricate interfaces. Run typecheck/unit/local fixture tests/full build and fix integration bugs. Record actual readiness/results in IMPLEMENTATION.md; do not hide unfinished adapters or falsely label a no-op as a working feature. Commit scoped reviewed source/lockfiles, build, then install/reload only from permanent package path when checks pass and initialization is safe (missing prerequisites must not trigger automatic unsafe installs). Verify plugin list and other local plugin paths/status, ensure removed computer-use BB plugins stay absent. Use actual remote UI testing if a safe supported harness is available; otherwise record the unverified check. Never public-share CDP/driver sockets. Return commands, live evidence, commit, and unresolved issues.\nFOUNDATION:\n` + foundation + `\nENGINE:\n` + implementations[0] + `\nUI/MEDIA:\n` + implementations[1], { provider: "codex", model: "gpt-5.6-sol", reasoningLevel: "high", label: "Integrate and verify BB plugin", phase: "Integration" });
phase("Review");
const review = await agent(common + `\nSTEP 5: Independent READ-ONLY release review. Do not edit/stage/commit files or deploy. Inspect the actual integrated Wayfinder implementation against PLAN.md and user requirements. Run safe independent checks. Find concrete correctness/security/performance defects with file locations and repro, especially host-wide lock across threads, forged approvals, stale target dispatch, scope/path escapes, secret capture/model leaks, crash/timeout lifecycle, fake SDK UI wiring, arbitrary native/FS actions, live media backpressure, range responses, artifact auth/sharing/expiry and copy/download behavior. Verify whether real browser and native fixtures and remote frontend actually ran; mocks are not live coverage. Distinguish release blockers from optional improvements. Return a bounded actionable verdict with severity, files, tests run, and missing evidence.\nINTEGRATION REPORT:\n` + integration, { provider: "claude-code", model: "claude-opus-5", reasoningLevel: "high", label: "Independent release review", phase: "Review" });
phase("Fix and verify");
const final = await agent(common + `\nSTEP 6: Fix verified release-review findings with regression tests, then rerun checks and safe live workflows. Own Wayfinder files serially. Inspect each finding, do not blindly apply speculative changes. Complete missing functional wiring where possible and never silently drop requested desktop, FS, Computer tab, inline media, or share features. Keep one controller, no unauthorized side effects, and no removed-plugin reinstall. Update IMPLEMENTATION.md and PLAN status accurately, commit only scoped changes, build/reload if safe, and verify actual plugin status. Do not push. If Infisical/provider/native/SDK limitations prevent real completion, clearly mark release blocked and give the exact prerequisite; don't make a feature-complete claim. Final response must state delivered features, tests and live checks actually run, performance measurements or lack thereof, commits, deployment status, remaining blockers and next action.\nINTEGRATION:\n` + integration + `\nINDEPENDENT REVIEW:\n` + review, { provider: "codex", model: "gpt-5.6-sol", reasoningLevel: "high", label: "Fix regressions and verify delivery", phase: "Fix and verify" });
return { foundation, implementations, integration, review, final };
