export const meta = {
  name: "wayfinder-finish",
  description: "Finish the existing minimal browser slice with lower-cost models, then review and fix concrete defects.",
  phases: [{ title: "Finish browser slice" }, { title: "Focused review" }, { title: "Fix and verify" }]
};
const context = `Work in /home/g4f4r0/projects/bb-plugins. Read README.md, applicable plugin skills and current SDK declarations. Read the TOP YAGNI override in bb-plugin-wayfinder/PLAN.md: it supersedes the broad plan and old workflow. User wants minimal clean production code and less token use. Existing engine/UI code is in the working tree, much untracked; preserve and reuse it. IMPLEMENTATION.md and OWNERSHIP.md describe contracts. Previous integration thread thr_9ntdx8ur74 is stopped and idle; you are the only writer when assigned writes. No nested agents, no speculative frameworks, no broad rewrite. Deliver only Fortress -> one task -> deterministic verification -> Computer live view -> inline screenshot copy/download, with basic single-controller ownership, privacy, bounded execution, cancel and cleanup. Defer desktop/OCR/advanced FS/sharing/video/benchmark expansion. Removed cua-driver/browse/browser-automation BB plugins stay uninstalled. A REAL existing Fortress executable was found at /home/g4f4r0/.bb/plugins/browse/host-data/browsers/fortress/v151.0.7908.0/linux-x64/tilion-fortress/tilion (chrome adjacent). Do not infer browser absence from bb browser instances being empty. Inspect the retained Browse launcher code for correct launch details, then use an owned fresh temporary profile, never the user's persistent profile. Do not expose CDP or install from temporary paths. Secret access must use Infisical with verified project, explicit env and narrow path; missing auth/scope is an explicit blocker, not permission to guess or print secrets. No real external mutations. No push. Return concise actual evidence and blockers, max 700 words.`;
const integrated = await agent(context + `\nFinish the minimal integration now. Inspect existing server.ts/host.ts/app.tsx/package and engine APIs, wire the supported BB SDK routes/tools/UI using existing modules, fix typecheck/test seams and avoid importing deferred features. Launch real Fortress on a local synthetic fixture, verify CDP/independent assertions/capture and cleanup even if the Jev credential remains unavailable; label deterministic fixture checks honestly, never call them a live Jev run. Keep browser warm only under explicit ownership. Run focused tests, typecheck and build. If safe, commit scoped reviewed code then build/install from permanent Wayfinder source and verify status; no broken or fake feature advertising. Update IMPLEMENTATION.md with concise results. Stop expanding when prerequisites prevent the remaining live test and report the exact missing prerequisite.`, {
  provider: "codex", model: "gpt-5.6-luna", reasoningLevel: "medium", label: "Finish existing browser integration", phase: "Finish browser slice"
});
const review = await agent(context + `\nREAD-ONLY focused review of the actual minimal delivery. No edits, deployment or new scope. Run relevant checks and inspect concrete failures: real SDK binding, private CDP, run ownership, stale input, cancel/cleanup, secret capture, screenshot auth/download/copy and live-view backpressure. Distinguish actual live results from mocks. Return only actionable blockers with file references or a concise no-blocker finding; deferred features are not defects.\nIntegration report:\n` + integrated, {
  provider: "claude-code", model: "claude-sonnet-5", reasoningLevel: "low", label: "Review minimal browser slice", phase: "Focused review"
});
const final = await agent(context + `\nFix only verified review blockers, add focused regressions and rerun tests/typecheck/build. No additional features. Review actual code before acting. Update implementation results, commit scoped changes, build/reload permanent source only if safe and verify live status. Give final delivered/not-delivered facts, tests, commits and exact remaining live prerequisites.\nIntegration:\n` + integrated + `\nReview:\n` + review, {
  provider: "codex", model: "gpt-5.6-luna", reasoningLevel: "medium", label: "Fix and verify", phase: "Fix and verify"
});
return { integrated, review, final };
